[Reference](https://towardsdatascience.com/20-of-numpy-functions-that-data-scientists-use-80-of-the-time-d8bd9c7d144b)

In [52]:
import numpy as np
import pandas as pd

# #1 Numpy Array Creation Methods


## 1/n: Create a NumPy array from a python list


In [53]:
a = [1, 2, 3]
np.array(a)

array([1, 2, 3])

In [54]:
a = [1, 2, 3]
type(np.array(a))

numpy.ndarray

In [55]:
a = [[1,2,3], [4,5,6]]
np.array(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a = [[1,2,3], [4,5,6]]
np.array(a, dtype = np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

## 2/n: Create a NumPy array of Zeros


In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## 3/n: Create a NumPy array of Ones


In [59]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## 4/n: Create an Identity Numpy Array


In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5/n: Create an equally spaced Numpy Array with a specific step


In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [63]:
np.arange(5, 11, 2)

array([5, 7, 9])

## 6/n: Create an equally spaced Numpy Array with a specific array size


In [64]:
np.linspace(start = 10, stop = 20, num = 5)

array([10. , 12.5, 15. , 17.5, 20. ])

## 7/n: Generate a random numpy array


In [65]:
np.random.randint(low = 5, high = 16, size = 5)

array([ 9, 14,  6, 14,  8])

In [66]:
np.random.random(size = 10)

array([0.24157292, 0.81108708, 0.49576498, 0.506603  , 0.73011095,
       0.48800441, 0.34341007, 0.2807585 , 0.14171665, 0.06952923])

## 8/n: Generate NumPy Array from a Pandas Series


In [67]:
s = pd.Series([1,2,3,4], name = "col")
np.array(s)

array([1, 2, 3, 4])

In [68]:
s = pd.Series([1,2,3,4], name = "col")
np.asarray(s)

array([1, 2, 3, 4])

# #2 NumPy Array Manipulation Methods


## 1/n: Shape of the NumPy Array


In [69]:
a = np.ones((2, 3))
print("Shape of the array - Method 1:", np.shape(a))
print("Shape of the array - Method 2:", a.shape)

Shape of the array - Method 1: (2, 3)
Shape of the array - Method 2: (2, 3)


## 2/n: Reshape the NumPy Array


In [70]:
a = np.arange(10)
a.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 3/n: Transpose the NumPy Array


In [71]:
a = np.arange(12).reshape((6, 2))
a.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [72]:
a = np.arange(12).reshape((6, 2))
a.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## 4/n: Concatenate multiple NumPy arrays to form one NumPy Array


In [73]:
## Concatenate Row-wise

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
## Concatenate Column-wise

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [75]:
## Concatenate to generate a flat NumPy Array

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

## 5/n: Flatten NumPy Array


In [76]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

## 6/n: Unique Elements of a NumPy Array


In [77]:
a = np.array([[1, 2], [2, 3]])
np.unique(a)

array([1, 2, 3])

In [78]:
## Return Unique Rows

a = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [79]:
## Return Unique Columns

a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
np.unique(a, axis=1)

array([[1, 3],
       [1, 3],
       [1, 4]])

## 7/n: Squeeze a NumPy Array


In [80]:
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [81]:
np.squeeze(x).shape

(3,)

## 8/n: Transform NumPy Array to Python List


In [82]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
a.tolist()

[[1, 1, 3], [1, 1, 3], [1, 1, 4]]

# #3 Mathematical Operations on NumPy Arrays


## 1/n: Trigonometric Functions

In [83]:
a = np.array([1,2,3])
print("Trigonometric Sine   :", np.sin(a))
print("Trigonometric Cosine :", np.cos(a))
print("Trigonometric Tangent:", np.tan(a))

Trigonometric Sine   : [0.84147098 0.90929743 0.14112001]
Trigonometric Cosine : [ 0.54030231 -0.41614684 -0.9899925 ]
Trigonometric Tangent: [ 1.55740772 -2.18503986 -0.14254654]


## 2/n: Rounding Functions


In [84]:
a = np.linspace(1, 2, 5)


print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

[1. 1. 1. 1. 2.]
[1. 2. 2. 2. 2.]
[1. 1. 2. 2. 2.]


## 3/n: Exponents and logarithms


In [85]:
a = np.arange(1, 6)

print(np.exp(a).round(2))
print(np.log(a).round(2))

[  2.72   7.39  20.09  54.6  148.41]
[0.   0.69 1.1  1.39 1.61]


# 4/n: Sum and Product


In [86]:
a = np.array([[1, 2], [3, 4]])

print(np.sum(a))
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

10
[4 6]
[3 7]


In [87]:
a = np.array([[1, 2], [3, 4]])

print(np.prod(a))
print(np.prod(a, axis = 0))
print(np.sum(a, axis = 1))

24
[3 8]
[3 7]


## 5/n: Square Root


In [88]:
a = np.array([[1, 2], [3, 4]])
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

# #4 Matrix and Vector Operations

## 1/n: Dot Product

In [89]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])
np.dot(a, b)

array([[3, 3],
       [7, 7]])

## 2/n: Matrix Product


In [90]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np.matmul(a, b)

array([[3, 3],
       [7, 7]])

In [91]:
a@b

array([[3, 3],
       [7, 7]])

## 3/n: Vector Norm


In [92]:
a = np.arange(-4, 5)

print(np.linalg.norm(a)) ## L2 Norm
print(np.linalg.norm(a, 1)) ## L1 Norm

7.745966692414834
20.0


# #5 Sorting Methods


## 1/n: Sort a NumPy Array


In [93]:
a = np.array([[1,4],[3,1]])

print(np.sort(a)) ## sort based on rows
print(np.sort(a, axis=None)) ## sort the flattened array
print(np.sort(a, axis=0)) ## sort based on columns

[[1 4]
 [1 3]]
[1 1 3 4]
[[1 1]
 [3 4]]


## 2/n: Order of Indices in a Sorted NumPy Array


In [94]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

# #6 Searching Methods


## 1/n: Indices corresponding to Maximum Values


In [95]:
a = np.random.randint(1, 20, 10).reshape(2,5)

print(np.argmax(a)) ## index in a flattend array
print(np.argmax(a, axis=0)) ## indices along columns
print(np.argmax(a, axis=1)) ## indices along rows

6
[0 1 1 0 1]
[0 1]


In [96]:
ind = np.unravel_index(np.argmax(a), a.shape)
ind

(1, 1)

## 2/n: Indices corresponding to Minimum Values


In [97]:
a = np.random.randint(1, 20, 10).reshape(2,5)

print(np.argmin(a)) ## index in a flattend array
print(np.argmin(a, axis=0)) ## indices along columns
print(np.argmin(a, axis=1)) ## indices along rows

5
[1 1 0 0 1]
[2 0]


## 3/n: Search based on condition


In [98]:
a = np.random.randint(-10, 10, 10)
np.where(a < 0, 0, a)

array([0, 4, 0, 0, 0, 4, 6, 0, 0, 0])

## 4/n: Indices of Non-Zero Elements


In [99]:
a = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
np.nonzero(a)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

# #7 Statistical Methods


## 1/n: Mean


In [100]:
a = np.array([[1, 2], [3, 4]])

print(np.mean(a))
print(np.mean(a, axis = 1)) ## along the row axis
print(np.mean(a, axis = 0)) ## along the column axis

2.5
[1.5 3.5]
[2. 3.]


## 2/n: Median


In [101]:
a = np.array([[1, 2], [3, 4]])

print(np.median(a))
print(np.median(a, axis = 1)) ## along the row axis
print(np.median(a, axis = 0)) ## along the column axis

2.5
[1.5 3.5]
[2. 3.]


## 3/n: Standard Deviation


In [102]:
a = np.array([[1, 2], [3, 4]])

print(np.std(a))
print(np.std(a, axis = 1)) ## along the row axis
print(np.std(a, axis = 0)) ## along the column axis

1.118033988749895
[0.5 0.5]
[1. 1.]
