[Reference](https://medium.com/techtofreedom/3-uses-of-the-ellipsis-in-python-25795aac723d)

In [ ]:
...

Ellipsis

In [ ]:
Ellipsis

Ellipsis

In [ ]:
def write_an_article():
    ...


class Article:
    ...

In [ ]:
def write_an_article():
    pass


class Article:
    pass

In [ ]:
import numpy as np

A = np.random.rand(2, 3, 2)
print(A)

[[[0.24510886 0.12749783]
  [0.51061087 0.33229199]
  [0.6284961  0.97761928]]

 [[0.99843328 0.36596301]
  [0.03018566 0.60883873]
  [0.40258632 0.04382473]]]


In [ ]:
print(A[:, :, 1])

[[0.12749783 0.33229199 0.97761928]
 [0.36596301 0.60883873 0.04382473]]


In [ ]:
print(A[..., 1])

[[0.12749783 0.33229199 0.97761928]
 [0.36596301 0.60883873 0.04382473]]


In [ ]:
print(A[Ellipsis, 1])

[[0.12749783 0.33229199 0.97761928]
 [0.36596301 0.60883873 0.04382473]]


In [ ]:
def partial(func: Callable[..., str], *args) -> Callable[..., str]:
    # Body