[Reference](https://levelup.gitconnected.com/5-powerful-python-one-liners-you-should-know-469b9c4737c7)

# 1- Typecasting of all items in a list

In [1]:
list(map(int, ['1', '2', '3']))

[1, 2, 3]

In [2]:
list(map(float, ['1', 2, '3.0', 4.0, '5', 6]))

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

# 2- Sum of digits of an integer

In [3]:
sum_of_digits = lambda x: sum(map(int, str(x)))

In [4]:
print(sum_of_digits(1789))

25


# 3- Flat a list that contains sublists

In [5]:
l = [[1, 2, 3], [4, 5], [6], [7, 8], [9]]

In [6]:
flattened_list = []
for sublist in l:
    for item in sublist:
        flattened_list.append(item)

In [8]:
l = [[1, 2, 3], [4, 5], [6], [7, 8], [9]]
flattened_list = [item for sublist in l for item in sublist]
print(flattened_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# 4- Transpose of a Matrix

In [9]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
transpose_A = [list(i) for i in zip(*A)]
transpose_A

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [10]:
import numpy as np

A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.matrix(A))
transpose_A = [list(i) for i in zip(*A)]
print()
print(np.matrix(transpose_A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 5- Swap keys and values in a dictionary

In [11]:
staff = {'Data Scientist': 'John', 'Django Developer': 'Jane'}
staff = {i:j for j, i in staff.items()}
print(staff)

{'John': 'Data Scientist', 'Jane': 'Django Developer'}
