[Reference](https://towardsdatascience.com/5-smart-python-numpy-functions-dfd1072d2cb4)

# 1) Use of -1 in Reshape

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
a.shape

(2, 4)

In [4]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [5]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [6]:
a.reshape(-1,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
a.reshape(2,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
a.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
a.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
a.reshape(2,-1,1)

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [12]:
a.reshape(-1,-1)

ValueError: ignored

In [13]:
a.reshape(3,-1)

ValueError: ignored

# 2) AArgpartition: Find N maximum values in an array

In [14]:
a = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
index = np.argpartition(a, -5)[-5:]
index

array([ 6,  1, 10,  7,  0])

In [15]:
np.sort(a[index])

array([ 5,  6,  7,  9, 10])

# 3) Clip: How to keep values in an array within an interval

In [16]:
a = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
print (np.clip(a,2,6))

[6 6 4 3 2 2 5 6 2 4 6 2]


In [17]:
a = np.array([10, -1, 4, -3, 2, 2, 5, 9, 0, 4, 6, 0])
print (np.clip(a,2,5))

[5 2 4 2 2 2 5 5 2 4 5 2]


# 4) Extract: To extract specific elements from an array based on condition

In [18]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Define the codition, here we take MOD 3 if zero
condition = np.mod(arr, 3)==0
condition

array([ True, False, False,  True, False, False,  True, False, False,
        True])

In [20]:
np.extract(condition, arr)

array([0, 3, 6, 9])

In [21]:
np.extract(((arr > 2) & (arr < 8)), arr)

array([3, 4, 5, 6, 7])

# 5) setdiff1d: How to find unique values in an array compared to another

In [22]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([3,4,7,6,7,8,11,12,14])
c = np.setdiff1d(a,b)
c

array([1, 2, 5, 9])