[Reference](https://ai.plainenglish.io/data-transformation-in-pandas-29b2b3c61b34)

In [1]:
import pandas as pd

In [2]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [3]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [4]:
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [5]:
data["c"]=range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [6]:
data.duplicated(["a","b"],keep="last")

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [7]:
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [8]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [9]:
n=df["names"].str.capitalize()

In [10]:
df["branches"]=n.map(classes)
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [11]:
s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [12]:
import numpy as np

In [13]:
s.replace(70,np.nan)

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [14]:
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [15]:
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [17]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [18]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [19]:
df.rename(index=str.title,columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [20]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
          inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

In [21]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85]
x=[20,40,60,80,100]
y=pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [22]:
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [23]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [24]:
pd.value_counts(y)

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
dtype: int64

In [25]:
y=pd.cut(sc,x,right=False)
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [26]:
nm=["low", "medium", "high", "very high"]
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [27]:
pd.cut(sc,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] <
                                            (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] <
                                            (86.0, 93.0] < (93.0, 100.0]]

In [28]:
data=np.random.randn(100)
c=pd.qcut(data,4)
c

[(0.703, 2.488], (-3.758, -0.809], (-3.758, -0.809], (-3.758, -0.809], (0.703, 2.488], ..., (0.703, 2.488], (0.703, 2.488], (-0.103, 0.703], (-0.103, 0.703], (-0.809, -0.103]]
Length: 100
Categories (4, interval[float64, right]): [(-3.758, -0.809] < (-0.809, -0.103] < (-0.103, 0.703] <
                                           (0.703, 2.488]]

In [29]:
pd.value_counts(c)

(-3.758, -0.809]    25
(-0.809, -0.103]    25
(-0.103, 0.703]     25
(0.703, 2.488]      25
dtype: int64

In [30]:
data=pd.DataFrame(np.random.randn(1000,4))
data.head()

0         1         2         3
0  0.247426 -1.113987  1.258120  0.223959
1 -0.269587  0.051864 -0.403488 -1.079716
2  0.119023  1.190717  0.052452 -0.237820
3 -0.788035  0.951529 -0.106051 -0.819320
4  0.836776  1.832828  1.496271 -0.463341

In [31]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.060713    -0.016282    -0.017337     0.004008
std       0.983837     0.964104     1.015678     1.029972
min      -3.333075    -3.507527    -3.093468    -3.175515
25%      -0.755357    -0.661631    -0.735105    -0.735239
50%      -0.064061     0.001881    -0.039848    -0.038552
75%       0.571879     0.626718     0.656376     0.692596
max       3.563180     2.721418     3.043777     3.186410

In [32]:
col=data[1]
col[np.abs(col)>3]
data[(np.abs(data)>3).any(1)]

0         1         2         3
66  -3.333075 -0.876460  0.966660 -0.849196
282  1.193593 -0.579295  3.043777 -2.819175
290  3.563180  0.315972  0.027385 -1.878383
424 -0.914677 -0.815094  0.494104  3.022551
626 -1.568570  0.795682  0.575264  3.017170
659  0.689854 -0.892777  0.967225  3.186410
663 -1.524869 -3.507527 -0.753877  0.091612
671 -1.879780  0.098983 -3.093468  0.521753
788 -1.185290  1.157394  0.212194 -3.175515
800 -1.705544 -3.112702 -1.494637 -0.249290
912  0.808584  0.497722 -3.008398  0.251560

In [33]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1 -1.0  1.0 -1.0 -1.0
2  1.0  1.0  1.0 -1.0
3 -1.0  1.0 -1.0 -1.0
4  1.0  1.0  1.0 -1.0

In [34]:
data=pd.DataFrame(
    np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [35]:
rw=np.random.permutation(4)
rw

array([2, 1, 0, 3])

In [36]:
data.take(rw)

0   1   2
2  6   7   8
1  3   4   5
0  0   1   2
3  9  10  11

In [37]:
data.sample()

0  1  2
0  0  1  2

In [38]:
data.sample(n=2)

0  1  2
0  0  1  2
2  6  7  8

# Dummy Variable


In [39]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [40]:
pd.get_dummies(data["letter"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [41]:
data=np.random.randn(10)
data

array([ 0.86607225, -0.72195194, -0.39970166,  0.46867962,  0.50972242,
       -0.94975215,  1.08913767, -0.51393825, -1.09925444,  0.8154813 ])

In [42]:
pd.get_dummies(pd.cut(data,4))

(-1.101, -0.552]  (-0.552, -0.00506]  (-0.00506, 0.542]  (0.542, 1.089]
0                 0                   0                  0               1
1                 1                   0                  0               0
2                 0                   1                  0               0
3                 0                   0                  1               0
4                 0                   0                  1               0
5                 1                   0                  0               0
6                 0                   0                  0               1
7                 0                   1                  0               0
8                 1                   0                  0               0
9                 0                   0                  0               1