[Reference](https://medium.com/@WojtekFulmyk/normalizing-data-for-machine-learning-27aa69988772)

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import minmax_scale

# example df of 6 rows and 3 columns
df = pd.DataFrame(np.random.randn(6, 3))
normalized = minmax_scale(df)

print(normalized)

[[0.58188288 0.         0.39797058]
 [0.60472846 0.57108572 0.12449106]
 [0.         0.07194099 1.        ]
 [0.63365613 0.17524012 0.37293034]
 [0.25355013 0.11156149 0.91674555]
 [1.         1.         0.        ]]
