[Reference](https://medium.com/@WojtekFulmyk/standardizing-data-for-machine-learning-2cf687e621f9)

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# example df of 6 rows and 3 columns
df = pd.DataFrame(np.random.randn(6, 3))

scaler = StandardScaler()
scaler.fit(df)

# transforms the df
standardized = scaler.transform(df)

print(standardized)

[[-0.08661013 -0.56062517  1.59276076]
 [-1.35872574 -0.45468999 -1.18028139]
 [ 1.18947673 -0.93125799  0.0772955 ]
 [ 1.0861257  -0.84521636 -1.2097578 ]
 [-1.19203992  1.38406333  0.77313354]
 [ 0.36177336  1.40772618 -0.05315062]]
