[Reference](https://medium.com/nerd-for-tech/difference-fit-transform-and-fit-transform-method-in-scikit-learn-b0a4efcab804)

In [4]:
import numpy as np
from sklearn.impute import SimpleImputer
X = np.array([[90, 80, 100], [np.nan, 100, 70], [70, 90, np.nan]])
mean_imp = SimpleImputer(missing_values=np.nan, strategy='mean')
mean_imp.fit(X)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [6]:
print(mean_imp.transform(X))

[[ 90.  80. 100.]
 [ 80. 100.  70.]
 [ 70.  90.  85.]]


In [7]:
print(mean_imp.fit_transform(X))

[[ 90.  80. 100.]
 [ 80. 100.  70.]
 [ 70.  90.  85.]]
