[Reference](https://python.plainenglish.io/ellipsis-the-pythons-perfectly-valid-syntax-eee93093f8bb)

# 1. Slicing Multi-Dimensional Arrays


In [1]:
import numpy as np

# Create a 3x3x3 array
arr = np.arange(27).reshape(3, 3, 3)

# Use ... to select all elements from one slice
print(arr[..., 0])

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


# 2. A Stylish Placeholder for Future Code

In [2]:
def upcoming_feature():
    # More code will be added here soon!
    return ...  # This returns the Ellipsis object

# 3. Enhancing Type Annotations and Stubs


In [3]:
from typing import Tuple

def get_numbers() -> Tuple[int, ...]:
    return (1, 2, 3)

In [4]:
print(id(...))      # Always the same ID!
print(id(Ellipsis)) # Exactly the same ID!

9618656
9618656
