In [2]:
import numpy as np

my_array = np.array([1, 2, 3, 4])

print(my_array.dtype)

int64


In [3]:
my_array = np.array([1, 2, 3, 4])
print(my_array)

[1 2 3 4]


In [4]:
my_array = np.array([1, 2, 3, 4.5])
print(my_array)

[1.  2.  3.  4.5]


In [5]:
my_array = np.array([1, 2, 3, '4'])
print(my_array)

['1' '2' '3' '4']


In [6]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
my_array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(my_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [8]:
my_array = np.array([1, 2, 3, 4])
print(my_array[0])

1


In [9]:
my_array = np.array([1, 2, 3, 4])
print(my_array[0:2])

[1 2]


In [13]:
# returns every other element from the slice
my_array = np.array([1, 2, 3, 4])
print(my_array[:2])

[1 2]


In [14]:
# 3rd element on 1st dimensional array
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(my_array[0, 2])

3


In [15]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(my_array[1, 0:2])

[5 6]


In [16]:
# 4th element inside the 1st 1d array in the 2nd 2d array
my_array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(my_array[1, 0, 3])

12


In [17]:
my_array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(my_array[1][0][1::2])

[10 12]


In [19]:
my_list1 = [1, 2, 3, 4]
my_list2 = [1, 2, 3, 4]
print(f'List: {my_list1 + my_list2}')

my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(f'Array: {my_array1 + my_array2}')

List: [1, 2, 3, 4, 1, 2, 3, 4]
Array: [2 4 6 8]


In [20]:
my_list1 = [1, 2, 3, 4]
my_list2 = [1, 2, 3, 4]
print(f'List Single Element: {my_list1[1] + my_list2[1]}')

my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(f'Array Single Element: {my_array1[1] + my_array2[1]}')

List Single Element: 4
Array Single Element: 4


In [21]:
my_list1 = [1, 2, 3, 4]
my_list2 = [1, 2, 3, 4]
print(f'List: {my_list1 - my_list2}')

TypeError: ignored

In [22]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(f'Array: {my_array1 - my_array2}')

Array: [0 0 0 0]


In [23]:
my_list1 = [1, 2, 3, 4]
my_list2 = [1, 2, 3, 4]
print(f'List: {my_list1 * my_list2}')

TypeError: ignored

In [24]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(f'Array: {my_array1 * my_array2}')

Array: [ 1  4  9 16]


In [25]:
my_list1 = [1, 2, 3, 4]
my_list2 = [1, 2, 3, 4]
print(f'List: {my_list1 / my_list2}')

TypeError: ignored

In [26]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(f'Array: {my_array1 / my_array2}')

Array: [1. 1. 1. 1.]


In [27]:
my_list1 = [1, 2, 3, 4]
my_list2 = [1, 2, 3, 4]
print(f'List: {my_list1 ** my_list2}')

TypeError: ignored

In [28]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(f'Array: {my_array1 ** my_array2}')

Array: [  1   4  27 256]


In [29]:
my_list1 = [1, 2, 3, 4]
my_list2 = [1, 2, 3, 4]
print(f'List: {my_list1 % my_list2}')

TypeError: ignored

In [30]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(f'Array: {my_array1 % my_array2}')

Array: [0 0 0 0]


In [31]:
my_list1 = [1, 2, 3, 4]
my_list2 = [1, 2, 3, 4]
print(f'List: {my_list1 // my_list2}')

TypeError: ignored

In [32]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(f'Array: {my_array1 // my_array2}')

Array: [1 1 1 1]


In [33]:
# copy
my_array = np.array([1, 2, 3, 4])
array_copy = my_array.copy()
my_array[1] = 55

print(f'Original Array: {my_array}')
print(f'Copied Array: {array_copy}')

Original Array: [ 1 55  3  4]
Copied Array: [1 2 3 4]


In [34]:
# view
my_array = np.array([1, 2, 3, 4])
array_view = my_array.view()
my_array[1] = 55
print(f'Original Array: {my_array}')
print(f'Viewed Array: {array_view}')

Original Array: [ 1 55  3  4]
Viewed Array: [ 1 55  3  4]


In [35]:
my_array = np.array([1, 2, 3, 4])
for x in my_array:
    print(x)

1
2
3
4


In [36]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in my_array:
    for i in x:
        print(i)

1
2
3
4
5
6
7
8


In [37]:
my_array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
for x in my_array:
    for y in x:
         for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [38]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(np.concatenate((my_array1, my_array2)))

[1 2 3 4 1 2 3 4]


In [39]:
my_array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
my_array2 = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])
print(np.concatenate((my_array1, my_array2)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [40]:
my_array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
my_array2 = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])
print(np.concatenate((my_array1, my_array2), axis=1))

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [41]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(np.stack((my_array1, my_array2)))

[[1 2 3 4]
 [1 2 3 4]]


In [42]:
my_array1 = np.array([1, 2, 3, 4])
my_array2 = np.array([1, 2, 3, 4])
print(np.stack((my_array1, my_array2), axis=1))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [43]:
my_array = np.array([1, 2, 3, 4])
print(np.array_split(my_array, 2))

[array([1, 2]), array([3, 4])]


In [44]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(np.array_split(my_array, 2))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [45]:
my_array = np.array([1, 2, 3, 4])
print(np.where(my_array == 4))

(array([3]),)


In [46]:
my_array = np.array([50, 10, 20, 80])
print(np.sort(my_array))

[10 20 50 80]


In [47]:
my_array1 = np.array([1, 2, 3, 4])
filtered_array = my_array1 > 2
my_array2 = my_array1[filtered_array]
print(my_array2)

[3 4]


In [48]:
my_array = np.array([1, 2, 3, 4])
print(my_array.shape)

(4,)


In [49]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(my_array.shape)

(2, 4)


In [50]:
my_array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(my_array.shape)

(2, 2, 4)


In [51]:
my_array = np.array([1, 2, 3, 4])
print(my_array.reshape(2, 2))

[[1 2]
 [3 4]]


In [52]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(my_array.reshape(1,8))

[[1 2 3 4 5 6 7 8]]
