In [9]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

X = np.random.random((500,200))
y = np.random.randint(2,size=(500,1))

model = Sequential()
model.add(Dense(32,activation='relu',input_dim=200))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X,y,epochs=30,batch_size=20)

Epoch 1/30
25/25 [==============================] - 1s 1ms/step - loss: 0.7273 - accuracy: 0.4783
Epoch 2/30
25/25 [==============================] - 0s 2ms/step - loss: 0.6766 - accuracy: 0.5940
Epoch 3/30
25/25 [==============================] - 0s 1ms/step - loss: 0.6731 - accuracy: 0.5820
Epoch 4/30
25/25 [==============================] - 0s 1ms/step - loss: 0.6733 - accuracy: 0.6037
Epoch 5/30
25/25 [==============================] - 0s 2ms/step - loss: 0.6459 - accuracy: 0.6308
Epoch 6/30
25/25 [==============================] - 0s 1ms/step - loss: 0.6528 - accuracy: 0.6502
Epoch 7/30
25/25 [==============================] - 0s 2ms/step - loss: 0.6401 - accuracy: 0.6697
Epoch 8/30
25/25 [==============================] - 0s 1ms/step - loss: 0.6281 - accuracy: 0.6685
Epoch 9/30
25/25 [==============================] - 0s 1ms/step - loss: 0.6175 - accuracy: 0.6886
Epoch 10/30
25/25 [==============================] - 0s 1ms/step - loss: 0.6124 - accuracy: 0.6953
Epoch 11/30
25/25 [

In [2]:
predictions = model.predict(data)
predictions

array([[0.10303825],
       [0.12569094],
       [0.04993996],
       [0.84222305],
       [0.08783153],
       [0.55566645],
       [0.3386462 ],
       [0.43837786],
       [0.06655541],
       [0.3621927 ],
       [0.7894696 ],
       [0.5265203 ],
       [0.10063374],
       [0.7639845 ],
       [0.8436011 ],
       [0.233412  ],
       [0.9139538 ],
       [0.288057  ],
       [0.06730825],
       [0.79003274],
       [0.41715837],
       [0.0538688 ],
       [0.33754802],
       [0.33705622],
       [0.40352255],
       [0.25850788],
       [0.8623513 ],
       [0.07012782],
       [0.08799046],
       [0.34504378],
       [0.5618371 ],
       [0.22037533],
       [0.3388474 ],
       [0.7769252 ],
       [0.16835263],
       [0.11870959],
       [0.6141528 ],
       [0.34576958],
       [0.18823051],
       [0.8237426 ],
       [0.35628706],
       [0.06652543],
       [0.6017525 ],
       [0.7214651 ],
       [0.71175   ],
       [0.40308675],
       [0.3362186 ],
       [0.434

In [26]:
from keras.datasets import boston_housing, mnist, cifar10, imdb
(X_train,y_train),(X_test,y_test) = mnist.load_data()
(X_train_2,y_train_2),(X_test_2,y_test_2) = boston_housing.load_data()
(X_train_3,y_train_3),(X_test_3,y_test_3) = cifar10.load_data()
(X_train_4,y_train_4),(X_test_4,y_test_4) = imdb.load_data(num_words=20000)

<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.7/dist-packages/keras/datasets/imdb.py:155: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.7/dist-packages/keras/datasets/imdb.py:156: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the nda

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train_2)
X_standardized = scaler.transform(X_train_2)
X_test_standardized = scaler.transform(X_test_2)

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler().fit(X_train_2)
X_standardized = scaler.transform(X_train_2)
X_test_standardized = scaler.transform(X_test_2)

In [10]:
from sklearn.model_selection import train_test_split
X_train_5,X_test_5,y_train_5,y_test_5 = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
from tensorflow.keras.utils import to_categorical

num_classes = 10
y_train_ohe = to_categorical(y_train, num_classes)
y_test_ohe = to_categorical(y_test, num_classes)
print(y_train)
print(y_train_ohe)

[5 0 4 ... 5 6 8]
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [19]:
from keras.preprocessing import sequence

print(X_train_4)
X_train_4 = sequence.pad_sequences(X_train_4,maxlen=80)
X_test_4 = sequence.pad_sequences(X_test_4,maxlen=80)
print(X_train_4)

[list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32])
 list([1, 194, 1153, 194, 8255, 78, 228, 

In [20]:
from keras.models import Sequential
model = Sequential()

In [21]:
from keras.layers import Dense
model.add(Dense(20, input_dim=10,kernel_initializer='uniform',activation='relu'))
model.add(Dense(10,kernel_initializer='uniform',activation='relu'))
model.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_5 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
Total params: 441
Trainable params: 441
Non-trainable params: 0
_________________________________________________________________


In [22]:
from keras.layers import Dropout
model.add(Dense(312,activation='relu',input_shape=(130,)))
model.add(Dropout(0.3))
model.add(Dense(312,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(5,activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_5 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
_________________________________________________________________
dense_7 (Dense)              (None, 312)               624       
_________________________________________________________________
dropout (Dropout)            (None, 312)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 312)               97656     
_________________________________________________________________
dropout_1 (Dropout)          (None, 312)              

In [23]:
model.add(Dense(32,activation='relu',input_dim=X.shape[1]))
model.add(Dense(1))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_5 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
_________________________________________________________________
dense_7 (Dense)              (None, 312)               624       
_________________________________________________________________
dropout (Dropout)            (None, 312)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 312)               97656     
_________________________________________________________________
dropout_1 (Dropout)          (None, 312)              

In [29]:
X_train.shape[1:]

(28, 28)

In [42]:
(X_train,y_train),(X_test,y_test) = cifar10.load_data()

model = Sequential() 
model.add(Conv2D(32, (3,3), input_shape=X_train.shape[1:], activation='relu', padding='same'))
model.add(Conv2D(64, (3,3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(num_classes, activation='softmax'))

In [40]:
from tensorflow.keras import layers
from tensorflow import keras

model = keras.Sequential()
model.add(layers.Embedding(input_dim=1000, output_dim=64))
model.add(layers.LSTM(128))
model.add(layers.Dense(10))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          64000     
_________________________________________________________________
lstm (LSTM)                  (None, 128)               98816     
_________________________________________________________________
dense (Dense)                (None, 10)                1290      
Total params: 164,106
Trainable params: 164,106
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.output_shape

(None, 1)

In [33]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_5 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
_________________________________________________________________
dense_7 (Dense)              (None, 312)               624       
_________________________________________________________________
dropout (Dropout)            (None, 312)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 312)               97656     
_________________________________________________________________
dropout_1 (Dropout)          (None, 312)              

In [34]:
model.get_config()

{'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 10),
    'dtype': 'float32',
    'name': 'dense_4_input',
    'ragged': False,
    'sparse': False}},
  {'class_name': 'Dense',
   'config': {'activation': 'relu',
    'activity_regularizer': None,
    'batch_input_shape': (None, 10),
    'bias_constraint': None,
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_regularizer': None,
    'dtype': 'float32',
    'kernel_constraint': None,
    'kernel_initializer': {'class_name': 'RandomUniform',
     'config': {'maxval': 0.05, 'minval': -0.05, 'seed': None}},
    'kernel_regularizer': None,
    'name': 'dense_4',
    'trainable': True,
    'units': 20,
    'use_bias': True}},
  {'class_name': 'Dense',
   'config': {'activation': 'relu',
    'activity_regularizer': None,
    'bias_constraint': None,
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_regularizer': None,
    'dtype': 'float32',
    'kernel_constrain

In [35]:
model.get_weights()

[array([[ 0.04998102,  0.02122675,  0.04989929, -0.02258054, -0.01826371,
          0.04701379, -0.03153287,  0.04823904,  0.02056995, -0.04931296,
          0.03616672,  0.03748432, -0.03670614, -0.00977578, -0.02321645,
          0.00400265,  0.00860678, -0.03468993,  0.04081848,  0.03750639],
        [-0.02398409,  0.00545434, -0.01268093,  0.0052041 ,  0.04204014,
          0.01335848, -0.01409198, -0.00936712, -0.01008823, -0.03335428,
          0.0247294 , -0.03272804, -0.0319671 , -0.04743978, -0.0097419 ,
          0.01003852,  0.008015  ,  0.0249277 ,  0.01479984, -0.02414621],
        [-0.04360923,  0.02679363,  0.04332739,  0.03156785,  0.01170565,
         -0.02106686,  0.02281258, -0.01686062,  0.02070976,  0.0282116 ,
         -0.01691191, -0.00864489, -0.04238596, -0.04918033,  0.00835501,
         -0.02680458, -0.04035689,  0.04894341,  0.0262743 ,  0.01942773],
        [ 0.01669909, -0.04146622,  0.00250985,  0.03743919, -0.03846606,
         -0.03065727,  0.00393426, 

In [ ]:
# Binary Classification
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# Multi-class Classification
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
# Regression
model.compile(optimizer='rmsprop', loss='mae', metrics=['mae'])

In [37]:
from keras.optimizers import SGD
sgd = SGD(learning_rate=0.001, decay=1e-5, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

In [38]:
from keras.models import load_model
model.save('example_model.h5')
example_model = load_model('example_model.h5')

In [ ]:
from keras.callbacks import EarlyStopping

es = EarlyStopping(patience=2)
history = model.fit(X_train,y_train, batch_size=40, epochs=20, 
                    validation_data=(X_test,y_test),callbacks=[es])