[Reference](https://medium.com/@nandeda.narayan/mastering-numpy-part-4-array-broadcasting-faf8dabee7ef)

In [1]:
import numpy as np

# Create an array with missing values
arr = np.array([1, 2, -999, 4, 5])

# Create a mask for invalid values
mask = arr == -999

# Create a masked array
masked_arr = np.ma.masked_array(arr, mask=mask)
print("Masked array:", masked_arr)
print("Valid values:", masked_arr.data)

Masked array: [1 2 -- 4 5]
Valid values: [   1    2 -999    4    5]


In [2]:
import numpy as np

# Create an array
arr = np.array([5, 3, 1, 4, 2])

# Sort the array
sorted_arr = np.sort(arr)

# Print the sorted array
print(sorted_arr)

[1 2 3 4 5]


In [3]:
import numpy as np

# Create an array
arr = np.array([5, 3, 1, 4, 2])

# Sort the array in place
arr.sort()

# Print the sorted array
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_elements, counts = np.unique(arr, return_counts=True)

In [5]:
import numpy as np

# Define a function that operates on a single element
def square(x):
    return x ** 2

# Create an input array
arr = np.array([1, 2, 3, 4, 5])

# Use numpy.vectorize() to vectorize the square function
vec_square = np.vectorize(square)

# Apply the vectorized function to the array
result = vec_square(arr)

print(result)

[ 1  4  9 16 25]


In [6]:
import numpy as np

# Create an input array
arr = np.array([1, 2, 3, 4, 5])

# Create a condition
condition = arr % 2 == 0

# Create two arrays to choose values from based on the condition
x = np.array([10, 20, 30, 40, 50])
y = np.array([100, 200, 300, 400, 500])

# Use numpy.where() to select elements based on the condition
result = np.where(condition, x, y)

print(result)

[100  20 300  40 500]


In [7]:
import numpy as np

# Create an input array
arr = np.array([1, 2, 3, 4, 5])

# Create a condition
condition = arr % 2 == 0

# Use numpy.where() with scalar values
result = np.where(condition, 10, -10)

print(result)

[-10  10 -10  10 -10]


In [8]:
import numpy as np

# Create two input arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the cross product using numpy.cross()
cross_product = np.cross(a, b)

print(cross_product)

[-3  6 -3]


In [9]:
import numpy as np

# Create two multidimensional input arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

# Compute the cross product along the last axis using numpy.cross()
cross_product = np.cross(a, b)

print(cross_product)

[[-6 12 -6]
 [-6 12 -6]]


In [10]:
import numpy as np

# Data points
xp = [1, 3, 4, 7]
fp = [2, 0, 5, 1]

# X-coordinates for interpolation
x = [1.5, 2.5, 4.5, 6]

# Interpolate values
interpolated_values = np.interp(x, xp, fp)

print(interpolated_values)

[1.5        0.5        4.33333333 2.33333333]


In [11]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the array using ravel()
flattened = np.ravel(arr)

print(flattened)

[1 2 3 4 5 6]


In [12]:
import numpy as np

# Example arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# Calculate correlation coefficient
correlation_matrix = np.corrcoef(x, y)
correlation_coefficient = correlation_matrix[0, 1]

print(correlation_coefficient)

-0.9999999999999999


In [13]:
import numpy as np

# Save an array
arr = np.array([1, 2, 3, 4, 5])
np.save("my_array.npy", arr)

# Load the array
loaded_arr = np.load("my_array.npy")

print(loaded_arr)

[1 2 3 4 5]
