[Reference](https://python.plainenglish.io/mastering-numpy-a-comprehensive-guide-to-efficient-array-processing-part-2-2-627393d34169)

In [1]:
import numpy as np

# Random Numbers

## Uniform Distribution

In [2]:
np.random.rand(10,3)

array([[0.81068992, 0.21965976, 0.24187751],
       [0.99531641, 0.5510162 , 0.00724949],
       [0.17144581, 0.98385599, 0.06204255],
       [0.39270937, 0.17099927, 0.94588561],
       [0.16686369, 0.5052114 , 0.49771808],
       [0.33502782, 0.20735866, 0.60113584],
       [0.99465189, 0.51349165, 0.89642503],
       [0.80046979, 0.08070862, 0.34688772],
       [0.84317147, 0.63624951, 0.7076355 ],
       [0.05114051, 0.15547766, 0.46465205]])

In [3]:
np.random.uniform(low=90, high=100, size=(5,5))

array([[95.71950626, 91.57278058, 93.2565776 , 98.38174848, 98.44141252],
       [96.40160741, 95.30401379, 93.48595809, 94.76960272, 99.22746968],
       [90.62093346, 97.10312323, 96.10356867, 93.82321544, 98.64376393],
       [91.31846417, 96.72175534, 97.04786101, 95.57662059, 96.54390814],
       [94.2218592 , 97.99175172, 96.17607191, 93.14469496, 96.3474536 ]])

In [4]:
np.histogram(np.random.uniform(size=(50000)))

(array([5018, 5041, 4953, 5012, 4905, 5000, 4987, 5048, 5004, 5032]),
 array([1.26451947e-05, 1.00008596e-01, 2.00004547e-01, 3.00000498e-01,
        3.99996449e-01, 4.99992400e-01, 5.99988351e-01, 6.99984302e-01,
        7.99980253e-01, 8.99976204e-01, 9.99972155e-01]))

## Normal Distribution

In [5]:
np.histogram(np.random.uniform(size=(50000)))

(array([5009, 4890, 5015, 4978, 5033, 4945, 5035, 4964, 5007, 5124]),
 array([2.38428929e-06, 9.99944719e-02, 1.99986559e-01, 2.99978647e-01,
        3.99970735e-01, 4.99962822e-01, 5.99954910e-01, 6.99946997e-01,
        7.99939085e-01, 8.99931173e-01, 9.99923260e-01]))

In [6]:
np.random.randn(6,4)

array([[ 0.55305649, -0.63182618, -0.06329199, -0.82313689],
       [-0.6098055 ,  1.97763103, -1.17445258, -0.84560122],
       [ 0.61437056, -0.14594593,  0.55699058,  0.34058306],
       [-1.63354209,  0.4880747 ,  0.47740153, -0.67998096],
       [ 0.12457732,  0.9315983 , -0.76323182, -0.84072169],
       [ 1.45149926, -0.37807368, -1.59101238, -0.44274434]])

In [7]:
np.random.normal(loc=8, scale=3, size=(5,5))

array([[ 7.07554875, 10.58571794,  9.71297179,  7.30496188,  9.68596723],
       [10.19374637,  4.59192343, 16.41195975,  9.08781189,  5.530913  ],
       [ 9.23327762, 12.85837205,  9.1817035 ,  9.19236622,  8.74287274],
       [ 6.25862609,  9.29472216,  8.60552366, 14.37234522,  2.81781487],
       [11.85711433,  6.14330654,  8.25736611,  8.44922021,  9.78684498]])

In [8]:
np.histogram(np.random.normal(loc=0, scale=1, size=50000))

(array([   36,   431,  2847,  9321, 15735, 13688,  6290,  1465,   173,
           14]),
 array([-4.02888089, -3.18990454, -2.35092819, -1.51195185, -0.6729755 ,
         0.16600085,  1.0049772 ,  1.84395354,  2.68292989,  3.52190624,
         4.36088259]))

## Random Integer

In [9]:
np.random.randint(low=5, high=10, size=(20,3))

array([[8, 5, 8],
       [6, 6, 6],
       [7, 6, 6],
       [6, 9, 6],
       [7, 7, 6],
       [5, 7, 6],
       [5, 5, 9],
       [8, 6, 8],
       [9, 5, 9],
       [5, 8, 6],
       [8, 5, 9],
       [5, 7, 5],
       [5, 7, 7],
       [5, 5, 9],
       [9, 8, 5],
       [5, 5, 8],
       [8, 6, 7],
       [8, 8, 5],
       [9, 7, 5],
       [8, 6, 9]])

## Array Shuffling

In [10]:
K = np.random.randint(1, 30, size=10)
K

array([13, 23,  6, 25,  2, 18, 14, 12, 22,  8])

In [11]:
print('K before shuffle\t: ', K)
np.random.shuffle(K)
print('K after shuffle\t\t: ', K)

K before shuffle	:  [13 23  6 25  2 18 14 12 22  8]
K after shuffle		:  [23 12  2  8 18 22  6 14 13 25]


## Random Choice

In [12]:
print(np.random.choice(K), end='\n\n')                #(1)
print(np.random.choice(K, size=(2,3)), end='\n\n')    #(2)
print(np.random.choice(K, size=(2,4), replace=False)) #(3)

8

[[18 23 12]
 [ 2 18  8]]

[[ 6 18  8 12]
 [ 2 22 23 25]]


## Seed

In [13]:
np.random.seed(99)
np.random.randint(low=0, high=10, size=(2,5))

array([[1, 3, 9, 8, 9],
       [8, 2, 4, 5, 4]])

In [14]:
np.random.seed(99)
np.random.randint(low=0, high=10, size=(2,5))

array([[1, 3, 9, 8, 9],
       [8, 2, 4, 5, 4]])

## View

In [15]:
L = np.array([55, 66, 77, 88, 99])
M = L
print(M)

[55 66 77 88 99]


In [16]:
M[0] = 15
print('L:', L)
print('M:', M)

L: [15 66 77 88 99]
M: [15 66 77 88 99]


## Copy

In [17]:
L = np.array([55, 66, 77, 88, 99])
M = L.copy()
M[0] = 15

print('L:', L)
print('M:', M)

L: [55 66 77 88 99]
M: [15 66 77 88 99]


# Mathematical Functions

## Basic Mathematical Operations

In [18]:
N = np.array([1,2,3], dtype='int32')
O = np.array([4,5,6], dtype='int32')

In [19]:
print(N + O)
print(N - O)
print(N * O)
print(N / O)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [20]:
print(np.add(N, O))
print(np.subtract(N, O))
print(np.multiply(N, O))
print(np.divide(N, O))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [21]:
print(N + 5)
print(N - 5)
print(N * 5)
print(N / 5)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


In [22]:
O = np.array([[2, 1, 0],
              [5, 4, 3],
              [8, 7, 6],
              [1, 0, 9]])

P = np.array([[4, 3],
              [6, 5],
              [8, 7]])

np.matmul(O, P)

array([[ 14,  11],
       [ 68,  56],
       [122, 101],
       [ 76,  66]])

In [23]:
Q = np.array([-56, 92, -24, -66, 72, -75, 90, 0, 32, 51])

print(np.sign(Q))
print(np.negative(Q))
print(np.abs(Q))      # Alternative: np.absolute()

[-1  1 -1 -1  1 -1  1  0  1  1]
[ 56 -92  24  66 -72  75 -90   0 -32 -51]
[56 92 24 66 72 75 90  0 32 51]


In [24]:
Q = np.array([-56, 92, -24, -66, 72, -75, 90, 0, 32, 51])

print(np.sign(Q))
print(np.negative(Q))
print(np.abs(Q))      # Alternative: np.absolute()

[-1  1 -1 -1  1 -1  1  0  1  1]
[ 56 -92  24  66 -72  75 -90   0 -32 -51]
[56 92 24 66 72 75 90  0 32 51]


## GCD and LCM

In [25]:
print(np.gcd(81, 72))    #(1)
print(np.lcm([3, 6, 9], 24))    #(2)
print(np.lcm([3, 12, 9], [24, 16, 3]))    #(3)

9
[24 24 72]
[24 48  9]


## Exponential Functions

In [26]:
print(np.power(8, 3))
print(np.power([1,2,3,4], 2))
print(np.power(144, 1/2))

512
[ 1  4  9 16]
12.0


In [27]:
print(np.power(8, 3))
print(np.power([1,2,3,4], 2))
print(np.power(144, 1/2))

512
[ 1  4  9 16]
12.0


## Angular Conversion and Trigonometric Functions

In [28]:
R = np.array([0, 90, 180, 270])    # Angles in degree
S = np.array([0, np.pi/2, np.pi, np.pi*3/2])    # Angles in radian

print(np.deg2rad(R))
print(np.rad2deg(S))

[0.         1.57079633 3.14159265 4.71238898]
[  0.  90. 180. 270.]


In [29]:
T = np.deg2rad([0, 45, 60])

print(np.sin(T))
print(np.cos(T))
print(np.tan(T))

[0.         0.70710678 0.8660254 ]
[1.         0.70710678 0.5       ]
[0.         1.         1.73205081]


## Logarithmic Functions

In [30]:
U = [1, 2, 10, np.e]

print(np.log(U))
print(np.log2(U))
print(np.log10(U))

[0.         0.69314718 2.30258509 1.        ]
[0.         1.         3.32192809 1.44269504]
[0.         0.30103    1.         0.43429448]


## Statistical Functions

In [31]:
V = np.array([1, 5, 4, 6, 8, 5, 4, 3, 2, 4, 7, 9, 5, 4, 3, 2, 0, 7, 9])

print('sum\t:', np.sum(V))
print('mean\t:', np.mean(V))
print('median\t:', np.median(V))
print('var\t:', np.var(V))
print('stddev\t:', np.std(V))
print('q1\t:', np.quantile(V, 0.25))
print('q2\t:', np.quantile(V, 0.5))
print('q3\t:', np.quantile(V, 0.75))
print('min\t:', np.min(V))
print('max\t:', np.max(V))

sum	: 88
mean	: 4.631578947368421
median	: 4.0
var	: 6.232686980609418
stddev	: 2.4965349948697733
q1	: 3.0
q2	: 4.0
q3	: 6.5
min	: 0
max	: 9


In [32]:
print('argmin\t:', np.argmin(V))
print('argmax\t:', np.argmax(V))

argmin	: 16
argmax	: 11


## Linear Algebra

In [33]:
W = np.array([10, 20, 30, 40])
X = np.array([3, 4, 5, 6])

In [34]:
np.dot(W, X)

500

In [35]:
print(np.inner(W, X))
print(np.outer(W, X))

500
[[ 30  40  50  60]
 [ 60  80 100 120]
 [ 90 120 150 180]
 [120 160 200 240]]


In [37]:
Y = np.array([[2, 1, 0],
              [0, 4, 5],
              [2, 6, 3]])

In [38]:
np.transpose(Y)

array([[2, 0, 2],
       [1, 4, 6],
       [0, 5, 3]])

In [39]:
np.linalg.inv(Y)

array([[ 0.69230769,  0.11538462, -0.19230769],
       [-0.38461538, -0.23076923,  0.38461538],
       [ 0.30769231,  0.38461538, -0.30769231]])

In [40]:
np.linalg.det(Y)

-25.99999999999999

In [41]:
eigenvalues, eigenvectors = np.linalg.eig(Y)

print(eigenvalues, end='\n\n')
print(eigenvectors)

[-1.75212771  1.6260023   9.12612541]

[[-0.17223211 -0.92394503 -0.09751686]
 [ 0.64623686  0.34555331 -0.69491737]
 [-0.74344739 -0.16406855 -0.71244671]]


# Logical and Bitwise Operators

## Logical Operators

In [43]:
Z = np.array([True, True, True])
AA = np.array([False, True, True])

In [44]:
print(np.logical_and(Z, AA))
print(np.logical_or(Z, AA))
print(np.logical_xor(Z, AA))

[False  True  True]
[ True  True  True]
[ True False False]


In [45]:
print('np.any(Z): ', np.any(Z))
print('np.all(Z): ', np.all(Z), end='\n\n')
print('np.any(AA):', np.any(AA))
print('np.all(AA):', np.all(AA))

np.any(Z):  True
np.all(Z):  True

np.any(AA): True
np.all(AA): False


In [47]:
AB = np.array([2, 0, 3, -5, 5, -1, 2, -4])

print(np.any(AB > 4))    #(1)
print(np.all(AB > 4))    #(2)

True
False


## Bitwise Operators

In [48]:
print(np.bitwise_and(12, 13))
print(np.bitwise_or(12, 13))
print(np.bitwise_xor(12, 13))

12
13
1


In [50]:
print(np.binary_repr(12))
print(np.binary_repr(13))

1100
1101


# Search and Sort

In [51]:
AC = np.array([9, 4, 5, 3, 2, 6, 8, 6, 5, 4, 5, 5, 3, 2])

mask = AC > 5  #(1)
mask

array([ True, False, False, False, False,  True,  True,  True, False,
       False, False, False, False, False])

In [52]:
AC[mask]

array([9, 6, 8, 6])

In [53]:
AC[AC > 5]

array([9, 6, 8, 6])

In [54]:
AC[(AC > 5) & (AC != 9)]

array([6, 8, 6])

In [55]:
AC[np.where((AC > 5) & (AC != 9))]

array([6, 8, 6])

In [56]:
np.where((AC > 5) & (AC != 9))

(array([5, 6, 7]),)

In [57]:
print(AC)
print(np.where(AC > 5, 0, AC+2))

[9 4 5 3 2 6 8 6 5 4 5 5 3 2]
[0 6 7 5 4 0 0 0 7 6 7 7 5 4]


In [58]:
np.unique(AC, return_counts=True)

(array([2, 3, 4, 5, 6, 8, 9]), array([2, 2, 2, 4, 2, 1, 1]))

## Sorting

In [59]:
AD = np.array([77,33,44,99,22,88,55,11,66])
AE = np.array(["Elon Musk", "Bill Gates", "Joe Biden", "Barack Obama"])

print(np.sort(AD))
print(np.sort(AE))

[11 22 33 44 55 66 77 88 99]
['Barack Obama' 'Bill Gates' 'Elon Musk' 'Joe Biden']


In [60]:
print(np.flip(np.sort(AD)))
print(np.flip(np.sort(AE)))

[99 88 77 66 55 44 33 22 11]
['Joe Biden' 'Elon Musk' 'Bill Gates' 'Barack Obama']


In [61]:
np.argsort(AD)

array([7, 4, 1, 2, 6, 8, 0, 5, 3])

In [62]:
AD[np.argsort(AD)]

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [63]:
AF = np.array([[3, 1, 5, 7],
               [8, 9, 3, 2],
               [4, 8, 2, 6]])

In [64]:
AG = np.arange(13)
AG

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
AG = np.arange(13)
AG

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Shape and Reshape

In [66]:
AH = np.array([[0,   1,  2,  3,  4,  5],
               [6,   7,  8,  9, 10, 11],
               [12, 13, 14, 15, 16, 17],
               [18, 19, 20, 21, 22, 23],
               [24, 25, 26, 27, 28, 29]])

len(AH)

5

In [67]:
AH.shape

(5, 6)

In [68]:
AH.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [69]:
AH.reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [70]:
AH.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [71]:
AH.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [72]:
AH.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [73]:
AH.flatten()[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [74]:
AH.flatten()[np.newaxis, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Concatenation and Splitting

In [75]:
AI = np.array(np.random.randint(0, 5, (2,4)))
AJ = np.array(np.random.randint(5, 10, (2,4)))

print(AI, end='\n\n')
print(AJ)

[[1 3 1 1]
 [0 3 3 4]]

[[7 5 9 5]
 [5 9 6 8]]


In [76]:
np.vstack((AI,AJ))

array([[1, 3, 1, 1],
       [0, 3, 3, 4],
       [7, 5, 9, 5],
       [5, 9, 6, 8]])

In [77]:
np.hstack((AI,AJ))

array([[1, 3, 1, 1, 7, 5, 9, 5],
       [0, 3, 3, 4, 5, 9, 6, 8]])

In [78]:
print(np.vstack((AI,AJ,AJ,AJ,AI)), end='\n\n')
print(np.hstack((AI,AJ,AJ,AJ,AI)))

[[1 3 1 1]
 [0 3 3 4]
 [7 5 9 5]
 [5 9 6 8]
 [7 5 9 5]
 [5 9 6 8]
 [7 5 9 5]
 [5 9 6 8]
 [1 3 1 1]
 [0 3 3 4]]

[[1 3 1 1 7 5 9 5 7 5 9 5 7 5 9 5 1 3 1 1]
 [0 3 3 4 5 9 6 8 5 9 6 8 5 9 6 8 0 3 3 4]]


In [79]:
print(np.append(AI, AJ), end='\n\n')
print(np.append(AI, AJ, axis=0), end='\n\n')
print(np.append(AI, AJ, axis=1))

[1 3 1 1 0 3 3 4 7 5 9 5 5 9 6 8]

[[1 3 1 1]
 [0 3 3 4]
 [7 5 9 5]
 [5 9 6 8]]

[[1 3 1 1 7 5 9 5]
 [0 3 3 4 5 9 6 8]]


In [80]:
print(np.concatenate([AI, AI, AI], axis=None), end='\n\n')
print(np.concatenate([AI, AI, AI]), end='\n\n')
print(np.concatenate([AI, AI, AI], axis=1))

[1 3 1 1 0 3 3 4 1 3 1 1 0 3 3 4 1 3 1 1 0 3 3 4]

[[1 3 1 1]
 [0 3 3 4]
 [1 3 1 1]
 [0 3 3 4]
 [1 3 1 1]
 [0 3 3 4]]

[[1 3 1 1 1 3 1 1 1 3 1 1]
 [0 3 3 4 0 3 3 4 0 3 3 4]]


## Splitting

In [81]:
AK = np.random.randint(0, 10, (20))
AK

array([7, 5, 4, 9, 1, 9, 0, 5, 9, 3, 3, 6, 2, 5, 0, 5, 1, 2, 1, 9])

In [82]:
np.split(AK, indices_or_sections=[3,5])

[array([7, 5, 4]),
 array([9, 1]),
 array([9, 0, 5, 9, 3, 3, 6, 2, 5, 0, 5, 1, 2, 1, 9])]

In [83]:
AL = np.random.randint(0, 10, (5,6))
AL

array([[1, 3, 8, 8, 9, 2],
       [9, 8, 0, 7, 3, 2],
       [0, 6, 0, 2, 3, 2],
       [8, 3, 5, 5, 9, 4],
       [1, 4, 9, 7, 6, 5]])

In [84]:
np.vsplit(AL, [2,4])

[array([[1, 3, 8, 8, 9, 2],
        [9, 8, 0, 7, 3, 2]]),
 array([[0, 6, 0, 2, 3, 2],
        [8, 3, 5, 5, 9, 4]]),
 array([[1, 4, 9, 7, 6, 5]])]

In [85]:
np.hsplit(AL, [3,4])

[array([[1, 3, 8],
        [9, 8, 0],
        [0, 6, 0],
        [8, 3, 5],
        [1, 4, 9]]),
 array([[8],
        [7],
        [2],
        [5],
        [7]]),
 array([[9, 2],
        [3, 2],
        [3, 2],
        [9, 4],
        [6, 5]])]