[Reference](https://medium.com/@nandeda.narayan/mastering-numpy-part-3-mathematical-operations-440f6c42a88)

# 1. Performing element-wise addition, subtraction, multiplication, and division on arrays

In [1]:
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Element-wise addition
addition_result = arr1 + arr2
print("Addition Result:")
print(addition_result)

# Element-wise subtraction
subtraction_result = arr1 - arr2
print("Subtraction Result:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = arr1 * arr2
print("Multiplication Result:")
print(multiplication_result)

# Element-wise division
division_result = arr1 / arr2
print("Division Result:")
print(division_result)

Addition Result:
[ 7  9 11 13 15]
Subtraction Result:
[-5 -5 -5 -5 -5]
Multiplication Result:
[ 6 14 24 36 50]
Division Result:
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# 2. Computing the sum, mean, and standard deviation of an array

In [2]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Computing the sum
sum_result = np.sum(arr)
print("Sum:", sum_result)

# Computing the mean
mean_result = np.mean(arr)
print("Mean:", mean_result)

# Computing the standard deviation
std_result = np.std(arr)
print("Standard Deviation:", std_result)

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


# 3. Finding the minimum and maximum values in an array

In [3]:
import numpy as np

# Creating a NumPy array
arr = np.array([5, 3, 8, 2, 7])

# Finding the minimum value
min_value = np.min(arr)
print("Minimum value:", min_value)

# Finding the maximum value
max_value = np.max(arr)
print("Maximum value:", max_value)

Minimum value: 2
Maximum value: 8


# 4. Computing the dot product of two arrays

In [4]:
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Computing the dot product
dot_product = np.dot(arr1, arr2)
print("Dot product:", dot_product)

Dot product: 32


# 5. Applying trigonometric functions (e.g., sine, cosine) to an array

In [5]:
import numpy as np

# Creating a NumPy array
arr = np.array([0, np.pi/2, np.pi])

# Applying sine function
sin_result = np.sin(arr)
print("Sine:", sin_result)

# Applying cosine function
cos_result = np.cos(arr)
print("Cosine:", cos_result)

Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


# 6. Calculating the exponential and logarithmic values of an array

In [6]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the exponential values
exp_arr = np.exp(arr)
print("Exponential values:", exp_arr)

# Calculate the logarithmic values
log_arr = np.log(arr)
print("Logarithmic values:", log_arr)


Exponential values: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithmic values: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


# 7. Applying element-wise comparisons between arrays using logical operators

In [7]:
import numpy as np

# Create two arrays
arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

# Element-wise logical AND
result_and = np.logical_and(arr1, arr2)
print("Element-wise logical AND:", result_and)

# Element-wise logical OR
result_or = np.logical_or(arr1, arr2)
print("Element-wise logical OR:", result_or)

Element-wise logical AND: [ True False False False]
Element-wise logical OR: [ True  True  True False]


# 8. Performing element-wise rounding of an array using numpy.round()

In [8]:
import numpy as np

# Create an array
arr = np.array([1.4, 2.7, 3.2, 4.8, 5.1])

# Perform element-wise rounding
rounded_arr = np.round(arr)
print("Rounded array:", rounded_arr)

Rounded array: [1. 3. 3. 5. 5.]


In [10]:
rounded_arr = np.round(arr, decimals=1)
rounded_arr

array([1.4, 2.7, 3.2, 4.8, 5.1])

# 9. Computing the element-wise absolute values of an array

In [11]:
import numpy as np

# Create an array
arr = np.array([-1, -2, 3, -4, 5])

# Compute element-wise absolute values
abs_arr = np.abs(arr)
print("Absolute values:", abs_arr)

Absolute values: [1 2 3 4 5]


# 10. Finding the index of the maximum and minimum values in an array using numpy.argmax() and numpy.argmin()

In [12]:
import numpy as np

# Create an array
arr = np.array([4, 2, 9, 1, 7])

# Find the index of the maximum value
max_index = np.argmax(arr)
print("Index of the maximum value:", max_index)

# Find the index of the minimum value
min_index = np.argmin(arr)
print("Index of the minimum value:", min_index)

Index of the maximum value: 2
Index of the minimum value: 3
