[Reference](https://python.plainenglish.io/matrix-calculation-with-python-5df443c8911f)

In [1]:
import numpy as np
a = np.array([1,2,3,4])
B = np.array([[1,2,3],[4,5,6]])

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
np.random.rand(2,3)

array([[0.79004803, 0.02364517, 0.64016094],
       [0.38144106, 0.96203541, 0.3275894 ]])

In [7]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A[0,1])

2


In [8]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A[:,1])

[ 2  6 10]


In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [10]:
A = np.array([[1,2,3],[4,5,6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
A = np.array([[1,2,3],[4,5,6], [5,8,9]])
np.linalg.inv(A)

array([[-0.5       ,  1.        , -0.5       ],
       [-1.        , -1.        ,  1.        ],
       [ 1.16666667,  0.33333333, -0.5       ]])

In [12]:
A = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([5, 6, 7])
A@b

array([38, 92])

In [13]:
# This is a 3x4 matrix
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# This is a 6x2 matrix
B = A.reshape((6,2))

In [14]:
a = np.linspace(0, 10, 100)