[Reference](https://medium.com/towards-artificial-intelligence/building-neural-networks-with-python-code-and-math-in-detail-ii-bbe8accbf3d1)

In [1]:
# Import required libraries :
import numpy as np
# Define input features :
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print (input_features.shape)
print (input_features)
# Define target output :
target_output = np.array([[0,1,1,1]])
# Reshaping our target output into vector :
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)
# Define weights :
# 6 for hidden layer
# 3 for output layer
# 9 total
weight_hidden = np.array([[0.1,0.2,0.3],
 [0.4,0.5,0.6]])
weight_output = np.array([[0.7],[0.8],[0.9]])
# Learning Rate :
lr = 0.05
# Sigmoid function :
def sigmoid(x):
 return 1/(1+np.exp(-x))
# Derivative of sigmoid function :
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))
 
for epoch in range(200000):
 # Input for hidden layer :
 input_hidden = np.dot(input_features, weight_hidden)
 
 # Output from hidden layer :
 output_hidden = sigmoid(input_hidden)
 
 # Input for output layer :
 input_op = np.dot(output_hidden, weight_output)
 
 # Output from output layer :
 output_op = sigmoid(input_op)
#==========================================================
 # Phase1
 
 # Calculating Mean Squared Error :
 error_out = ((1 / 2) * (np.power((output_op - target_output), 2)))
 print(error_out.sum())
 
 # Derivatives for phase 1 :
 derror_douto = output_op - target_output
 douto_dino = sigmoid_der(input_op) 
 dino_dwo = output_hidden
 derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)
#===========================================================
 # Phase 2 
 # derror_w1 = derror_douth * douth_dinh * dinh_dw1
 # derror_douth = derror_dino * dino_outh
 
 # Derivatives for phase 2 :
 derror_dino = derror_douto * douto_dino
 dino_douth = weight_output
 derror_douth = np.dot(derror_dino , dino_douth.T)
 douth_dinh = sigmoid_der(input_hidden) 
 dinh_dwh = input_features
 derror_wh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)
# Update Weights
 weight_hidden -= lr * derror_wh
 weight_output -= lr * derror_dwo # TODO: Verify update from derror_wo to derror_dwo
 
# Final hidden layer weight values :
print (weight_hidden)
# Final output layer weight values :
print (weight_output)
# Predictions :
#Taking inputs :
single_point = np.array([1,1])
#1st step :
result1 = np.dot(single_point, weight_hidden) 
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)
#=================================================
#Taking inputs :
single_point = np.array([0,0])
#1st step :
result1 = np.dot(single_point, weight_hidden) 
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)
#=====================================================
#Taking inputs :
single_point = np.array([1,0])
#1st step :
result1 = np.dot(single_point, weight_hidden) 
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)

Streaming output truncated to the last 5000 lines.
0.0002722171121700195
0.0002722156302065421
0.00027221414825905245
0.0002722126663275398
0.0002722111844120079
0.0002722097025124588
0.0002722082206288867
0.0002722067387612961
0.0002722052569096845
0.0002722037750740549
0.0002722022932543996
0.00027220081145072796
0.00027219932966303373
0.0002721978478913166
0.000272196366135578
0.00027219488439581886
0.0002721934026720349
0.0002721919209642301
0.000272190439272401
0.0002721889575965492
0.0002721874759366743
0.00027218599429277576
0.00027218451266485395
0.00027218303105290553
0.000272181549456937
0.00027218006787694106
0.0002721785863129203
0.00027217710476487285
0.00027217562323280075
0.000272174141716704
0.0002721726602165819
0.0002721711787324319
0.0002721696972642584
0.0002721682158120538
0.000272166734375822
0.0002721652529555682
0.0002721637715512822
0.0002721622901629716
0.0002721608087906303
0.000272159327434263
0.00027215784609386606
0.00027215636476943944
0.00027215488346098

In [2]:
# Import required libraries :
import numpy as np# Define input features :
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print (input_features.shape)
print (input_features)# Define target output :
target_output = np.array([[0,1,1,1]])# Reshaping our target output into vector :
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)# Define weights :
weights = np.array([[0.1],[0.2]])
print(weights.shape)
print (weights)# Define learning rate :
lr = 0.05# Sigmoid function :
def sigmoid(x):
    return 1/(1+np.exp(-x))# Derivative of sigmoid function :
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))# Main logic for neural network :
# Running our code 10000 times :for epoch in range(10000):
    inputs = input_features#Feedforward input :
    pred_in = np.dot(inputs, weights)#Feedforward output :
    pred_out = sigmoid(pred_in)#Backpropogation 
    #Calculating error
    error = pred_out - target_output
    x = error.sum()
    
    #Going with the formula :
    print(x)
    
    #Calculating derivative :
    dcost_dpred = error
    dpred_dz = sigmoid_der(pred_out)
    
    #Multiplying individual derivatives :
    z_delta = dcost_dpred * dpred_dz#Multiplying with the 3rd individual derivative :
    inputs = input_features.T
    weights -= lr * np.dot(inputs, z_delta)#Predictions :#Taking inputs :
single_point = np.array([1,0])
#1st step :
result1 = np.dot(single_point, weights) 
#2nd step :
result2 = sigmoid(result1)
#Print final result
print(result2)#====================================
#Taking inputs :
single_point = np.array([0,0])
#1st step :
result1 = np.dot(single_point, weights) 
#2nd step :
result2 = sigmoid(result1)
#Print final result
print(result2)#===================================
#Taking inputs :
single_point = np.array([1,1])
#1st step :
result1 = np.dot(single_point, weights) 
#2nd step :
result2 = sigmoid(result1)
#Print final result
print(result2)

(4, 2)
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
(4, 1)
[[0]
 [1]
 [1]
 [1]]
(2, 1)
[[0.1]
 [0.2]]
[0.52497919]
[0.5]
[0.57444252]


In [3]:
# Import required libraries :
import numpy as np
# Define input features :
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print (input_features.shape)
print (input_features)
# Define target output :
target_output = np.array([[0,1,1,0]])
# Reshaping our target output into vector :
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)
# Define weights :
# 8 for hidden layer
# 4 for output layer
# 12 total 
weight_hidden = np.random.rand(2,4)
weight_output = np.random.rand(4,1)
# Learning Rate :
lr = 0.05
# Sigmoid function :
def sigmoid(x):
 return 1/(1+np.exp(-x))
# Derivative of sigmoid function :
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))
# Main logic :
for epoch in range(200000):
 # Input for hidden layer :
 input_hidden = np.dot(input_features, weight_hidden)
 
 # Output from hidden layer :
 output_hidden = sigmoid(input_hidden)
 
 # Input for output layer :
 input_op = np.dot(output_hidden, weight_output)
 
 # Output from output layer :
 output_op = sigmoid(input_op)
#========================================================================
 # Phase1
 
 # Calculating Mean Squared Error :
 error_out = ((1 / 2) * (np.power((output_op - target_output), 2)))
 print(error_out.sum())
 
 
 # Derivatives for phase 1 :
 derror_douto = output_op - target_output
 douto_dino = sigmoid_der(input_op) 
 dino_dwo = output_hidden
 derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)
# ========================================================================
 # Phase 2
# derror_w1 = derror_douth * douth_dinh * dinh_dw1
 # derror_douth = derror_dino * dino_outh
 
 # Derivatives for phase 2 :
 derror_dino = derror_douto * douto_dino
 dino_douth = weight_output
 derror_douth = np.dot(derror_dino , dino_douth.T)
 douth_dinh = sigmoid_der(input_hidden) 
 dinh_dwh = input_features
 derror_dwh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)
# Update Weights
 weight_hidden -= lr * derror_dwh
 weight_output -= lr * derror_dwo
 
 
# Final values of weight in hidden layer :
print (weight_hidden)
# Final values of weight in output layer :
print (weight_output)
#Taking inputs :
single_point = np.array([0,-1])
#1st step :
result1 = np.dot(single_point, weight_hidden) 
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)
#Taking inputs :
single_point = np.array([0,5])
#1st step :
result1 = np.dot(single_point, weight_hidden) 
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)
#Taking inputs :
single_point = np.array([1,1.2])
#1st step :
result1 = np.dot(single_point, weight_hidden) 
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)

Streaming output truncated to the last 5000 lines.
0.0005423971999094038
0.0005423933174921195
0.0005423894351256868
0.0005423855528101046
0.0005423816705453659
0.0005423777883314817
0.000542373906168443
0.0005423700240562517
0.0005423661419949116
0.0005423622599844103
0.0005423583780247553
0.0005423544961159427
0.0005423506142579694
0.0005423467324508402
0.0005423428506945516
0.0005423389689891062
0.0005423350873344911
0.0005423312057307226
0.0005423273241777839
0.0005423234426756817
0.0005423195612244203
0.0005423156798239888
0.0005423117984743925
0.0005423079171756274
0.0005423040359276984
0.000542300154730594
0.0005422962735843247
0.0005422923924888803
0.0005422885114442652
0.0005422846304504765
0.000542280749507516
0.0005422768686153788
0.0005422729877740695
0.0005422691069835802
0.0005422652262439172
0.0005422613455550695
0.0005422574649170507
0.000542253584329849
0.0005422497037934669
0.0005422458233079006
0.000542241942873153
0.0005422380624892257
0.0005422341821561086
0.000542