[Reference](https://medium.com/@WojtekFulmyk/one-hot-encoding-a-brief-explanation-8c5daec395e3)

In [1]:
import numpy as np

colors = ['red', 'green', 'blue']

red = [1, 0, 0]
green = [0, 1, 0]
blue = [0, 0, 1]

print("Red encoding:", red)
print("Green encoding:", green)
print("Blue encoding:", blue)

Red encoding: [1, 0, 0]
Green encoding: [0, 1, 0]
Blue encoding: [0, 0, 1]


In [2]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

colors = ['red', 'green', 'blue']
# reshape as 2D array
colors = np.array(colors).reshape(-1,1)

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(colors)

print(encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
