[Reference](https://saket-shubham16.medium.com/python-numpy-starter-e4922450596c)

In [4]:
from datetime import datetime
a = [2,3,4]*100000000
b = [2,4,4]*100000000

start = datetime.now()
c = []
for ai,bi in zip(a,b):
    c.append(ai+bi)#total time taken
print(datetime.now()-start)

0:01:00.705471


In [5]:
from datetime import datetime
import numpy as np
a = [2,3,4]*100000000
b = [2,4,4]*100000000

start = datetime.now()
a = np.array(a)
b = np.array(b)
c = a+b#total time taken
print(datetime.now()-start)

0:00:45.350040


In [6]:
import numpy as np

a = np.array([1, 2, 3])
print("Type of the object: {} and shape: {}".format(type(a),a.shape))
print("elements in array {} {} {}".format(a[0], a[1], a[2]))

'''Changing values of element in the array'''
a[0] = 5
print("altered array: {}".format(a))

'''2D array'''
b = np.array([[1,2,3],[4,5,6]])
print("shape of the 2d array: {} ".format(b.shape))
print("{}, {}, {}".format(b[0, 0], b[0, 1], b[1, 0]))

Type of the object: <class 'numpy.ndarray'> and shape: (3,)
elements in array 1 2 3
altered array: [5 2 3]
shape of the 2d array: (2, 3) 
1, 2, 4


In [7]:

import numpy as np

# creating matrix from numpy methods
ones = np.ones((2,2))
print(ones)

zeros = np.zeros((2,3))
print(zeros)

mat = np.full((2,1), 7)
print(mat)

r_mat = np.random.random((3,3))  #creating random matrix
print(r_mat)

I = np.eye(3)  #identity matrix
print(I)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[7]
 [7]]
[[0.25872402 0.62601354 0.54690033]
 [0.5704232  0.73972276 0.16709626]
 [0.40614933 0.60037777 0.24781404]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
import numpy as np

np_matrix = np.random.randint(low=1,high=100,size=(5,5))
print(np_matrix)
# to get the first row
print(np_matrix[0,:])
# to get the first two rows
print(np_matrix[0:2,:])
# to get the first two rows and 2 columns
print(np_matrix[0:2,:2])

# to get first element
print(np_matrix[0,0])

[[95 90 19 66 13]
 [65 56 94 99 15]
 [65 84 83 17 73]
 [15 74 45  6  5]
 [57 44 24 18 93]]
[95 90 19 66 13]
[[95 90 19 66 13]
 [65 56 94 99 15]]
[[95 90]
 [65 56]]
95


In [9]:
import numpy as np

x = np.random.randint(low=1,high=10,size=(2,2))
y = np.random.randint(low=1,high=10,size=(2,2))


print(x + y)
print(np.add(x, y))


print(x - y)
print(np.subtract(x, y))


print(x * y)
print(np.multiply(x, y))


print(x / y)
print(np.divide(x, y))


print(np.sqrt(x))

[[13 12]
 [14 13]]
[[13 12]
 [14 13]]
[[ 1 -4]
 [ 2 -3]]
[[ 1 -4]
 [ 2 -3]]
[[42 32]
 [48 40]]
[[42 32]
 [48 40]]
[[1.16666667 0.5       ]
 [1.33333333 0.625     ]]
[[1.16666667 0.5       ]
 [1.33333333 0.625     ]]
[[2.64575131 2.        ]
 [2.82842712 2.23606798]]


In [10]:
import numpy as np

x = np.random.randint(low=1,high=10,size=(3,5))
print(x)
y = np.random.randint(low=1,high=10,size=(1,5))
print("\n",y)

print("\n",x+y)

[[7 7 7 3 8]
 [6 5 2 7 8]
 [8 7 7 3 4]]

 [[4 9 4 6 2]]

 [[11 16 11  9 10]
 [10 14  6 13 10]
 [12 16 11  9  6]]


In [11]:
import numpy as np

x = np.random.randint(low=1,high=10,size=(2,2))
y = np.random.randint(low=1,high=10,size=(2,2))
print(x)
print(y)
z = np.hstack((x,y))
print('\n',z)
v = np.vstack((x,y))
print('\n',v)

[[5 2]
 [8 3]]
[[4 8]
 [3 2]]

 [[5 2 4 8]
 [8 3 3 2]]

 [[5 2]
 [8 3]
 [4 8]
 [3 2]]


In [12]:
import numpy as np

def change_number(x):
    return x**2 + 3

x = np.random.randint(low=1,high=10,size=(5,5))
print(x)
z = np.vectorize(change_number)
print("\n",z(x))

[[4 3 8 5 4]
 [1 2 6 5 7]
 [8 9 2 8 4]
 [2 9 9 6 6]
 [7 3 6 7 9]]

 [[19 12 67 28 19]
 [ 4  7 39 28 52]
 [67 84  7 67 19]
 [ 7 84 84 39 39]
 [52 12 39 52 84]]
