[Reference](https://medium.com/@simranjeetsingh1497/the-ultimate-guide-to-machine-learning-from-eda-to-model-deployment-part-2-e56ac58785f8)

In [1]:
# from sklearn.decomposition import PCA

# # create a PCA object
# pca = PCA(n_components=2)

# # fit and transform the data
# X_pca = pca.fit_transform(X)

# # calculate the explained variance ratio
# print("Explained variance ratio:", pca.explained_variance_ratio_)

In [2]:
# from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# # create an LDA object
# lda = LinearDiscriminantAnalysis(n_components=1)

# # fit and transform the data
# X_lda = lda.fit_transform(X, y)

In [3]:
# import pandas as pd

# # calculate the correlation matrix
# corr_matrix = df.corr()

# # select highly correlated features
# high_corr = corr_matrix[abs(corr_matrix) > 0.8]

# # drop highly correlated features
# df = df.drop(high_corr.columns, axis=1)

In [7]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()
X, y = data.data, data.target

model = LinearRegression()
rfe = RFE(model, n_features_to_select=5)
rfe.fit(X, y)

# selected_features = data.feature_names[rfe.support_]
# print(selected_features)

RFE(estimator=LinearRegression(), n_features_to_select=5)

In [8]:
# from sklearn.ensemble import RandomForestRegressor

# # Load the data
# X, y = load_data()

# # Create a random forest regressor
# rf = RandomForestRegressor(n_estimators=100, random_state=42)

# # Fit the model
# rf.fit(X, y)

# # Get feature importances
# importances = rf.feature_importances_

# # Print feature importances
# for feature, importance in zip(X.columns, importances):
#     print(feature, importance)

In [9]:
from sklearn.svm import SVC
from sklearn.feature_selection import RFE
from sklearn.datasets import load_iris

# load the iris dataset
data = load_iris()
X = data.data
y = data.target

# create an SVM classifier
svm = SVC(kernel='linear')

# create a feature selector using RFE with SVM
selector = RFE(svm, n_features_to_select=2)

# fit the selector to the data
selector.fit(X, y)

# print the selected features
print(selector.support_)
print(selector.ranking_)

[False False  True  True]
[3 2 1 1]


In [11]:
# from sklearn.feature_selection import SequentialFeatureSelector
# from sklearn.linear_model import LinearRegression

# # Load the dataset
# X, y = load_dataset()

# # Initialize the feature selector
# selector = SequentialFeatureSelector(LinearRegression(), n_features_to_select=5, direction='forward')

# # Fit the feature selector
# selector.fit(X, y)

# # Print the selected features
# print(selector.support_)

In [12]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression

# Load the dataset
X, y = load_dataset()

# Initialize the feature selector
selector = SequentialFeatureSelector(LinearRegression(), n_features_to_select=5, direction='backward')

# Fit the feature selector
selector.fit(X, y)

# Print the selected features
print(selector.support_)

In [13]:
from itertools import combinations
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

# Load the dataset
X, y = load_dataset()

# Initialize variables
best_score = -float('inf')
best_features = None

# Loop over all possible subsets of features
for k in range(1, len(X.columns) + 1):
    for subset in combinations(X.columns, k):
        # Train a linear regression model
        X_subset = X[list(subset)]
        model = LinearRegression().fit(X_subset, y)
        # Compute the R2 score
        score = r2_score(y, model.predict(X_subset))
        # Update the best subset of features
        if score > best_score:
            best_score = score
            best_features = subset

# Print the best subset of features
print(best_features)

In [16]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()
X = data.data
y = data.target

# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Fit the Lasso model
lasso = Lasso(alpha=0.1)
lasso.fit(X, y)

# Get the coefficients
coefficients = lasso.coef_

In [18]:
from sklearn.linear_model import Ridge
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()
X = data.data
y = data.target

# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Fit the Ridge model
ridge = Ridge(alpha=0.1)
ridge.fit(X, y)

# Get the coefficients
coefficients = ridge.coef_

In [19]:
import pandas as pd

# create a sample dataframe
df = pd.DataFrame({
   'color': ['red', 'blue', 'green', 'red', 'yellow', 'blue']
})

# apply one-hot encoding
one_hot_encoded = pd.get_dummies(df['color'])
print(one_hot_encoded)

   blue  green  red  yellow
0     0      0    1       0
1     1      0    0       0
2     0      1    0       0
3     0      0    1       0
4     0      0    0       1
5     1      0    0       0


In [20]:
from sklearn.preprocessing import LabelEncoder

# create a sample dataframe
df = pd.DataFrame({
   'color': ['red', 'blue', 'green', 'red', 'yellow', 'blue']
})

# apply label encoding
label_encoder = LabelEncoder()
df['color_encoded'] = label_encoder.fit_transform(df['color'])
print(df)

    color  color_encoded
0     red              2
1    blue              0
2   green              1
3     red              2
4  yellow              3
5    blue              0


In [22]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 7.5 MB/s eta 0:00:00


In [24]:
# import category_encoders as ce

# # create a sample dataframe
# df = pd.DataFrame({
#    'size': ['S', 'M', 'L', 'XL', 'M', 'S']
# })

# # apply ordinal encoding
# ordinal_encoder = ce.OrdinalEncoder(cols=['size'], order=['S', 'M', 'L', 'XL'])
# df = ordinal_encoder.fit_transform(df)
# print(df)

In [25]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
scaler = StandardScaler()

# Fit and transform the data
X_scaled = scaler.fit_transform(X)

In [26]:
from sklearn.preprocessing import MinMaxScaler

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Fit and transform the data
X_scaled = scaler.fit_transform(X)

In [27]:
from sklearn.preprocessing import RobustScaler

# Create a RobustScaler object
scaler = RobustScaler()

# Fit and transform the data
X_scaled = scaler.fit_transform(X)

In [28]:
from sklearn.preprocessing import Normalizer

# Create a Normalizer object
scaler = Normalizer()

# Fit and transform the data
X_scaled = scaler.fit_transform(X)

In [29]:
import pandas as pd

# create a sample data frame
data = pd.DataFrame({'age': [25, 30, 35],
                     'income': [50000, 60000, 70000]})

# create a new interaction feature
data['age_income'] = data['age'] * data['income']

# display the updated data frame
print(data)

   age  income  age_income
0   25   50000     1250000
1   30   60000     1800000
2   35   70000     2450000


In [30]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# create a sample data set
X = np.array([[1, 2],
              [3, 4]])

# create polynomial features up to degree 2
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

# display the updated feature matrix
print(X_poly)

[[ 1.  1.  2.  1.  2.  4.]
 [ 1.  3.  4.  9. 12. 16.]]


In [31]:
import pandas as pd

# create a sample data frame
data = pd.DataFrame({'age': [20, 25, 30, 35, 40, 45, 50, 55]})

# create bins for different age groups
bins = [0, 18, 25, 35, 50, float('inf')]
labels = ['0-18', '18-25', '25-35', '35-50', '50+']
data['age_group'] = pd.cut(data['age'], bins=bins, labels=labels)

# display the updated data frame
print(data)

   age age_group
0   20     18-25
1   25     18-25
2   30     25-35
3   35     25-35
4   40     35-50
5   45     35-50
6   50     35-50
7   55       50+


In [33]:
# from sklearn.utils import resample

# # Upsample minority class
# X_upsampled, y_upsampled = resample(X_minority, y_minority, replace=True, n_samples=len(X_majority), random_state=42)

In [34]:
# from sklearn.utils import resample

# # Downsample majority class
# X_downsampled, y_downsampled = resample(X_majority, y_majority, replace=False, n_samples=len(X_minority), random_state=42)

In [36]:
# from imblearn.over_sampling import SMOTE

# # Use SMOTE to upsample minority class
# sm = SMOTE(random_state=42)
# X_resampled, y_resampled = sm.fit_resample(X, y)

In [37]:
import numpy as np
import pandas as pd
from scipy import stats

# Generate some skewed data
data = np.random.gamma(1, 10, 1000)

# Calculate skewness and kurtosis
skewness = stats.skew(data)
kurtosis = stats.kurtosis(data)

print("Skewness:", skewness)
print("Kurtosis:", kurtosis)

# Log transformation
log_data = np.log(data)
log_skewness = stats.skew(log_data)
log_kurtosis = stats.kurtosis(log_data)

print("Log Skewness:", log_skewness)
print("Log Kurtosis:", log_kurtosis)

# Square root transformation
sqrt_data = np.sqrt(data)
sqrt_skewness = stats.skew(sqrt_data)
sqrt_kurtosis = stats.kurtosis(sqrt_data)

print("Sqrt Skewness:", sqrt_skewness)
print("Sqrt Kurtosis:", sqrt_kurtosis)

# Box-Cox transformation
box_cox_data, _ = stats.boxcox(data)
box_cox_skewness = stats.skew(box_cox_data)
box_cox_kurtosis = stats.kurtosis(box_cox_data)

print("Box-Cox Skewness:", box_cox_skewness)
print("Box-Cox Kurtosis:", box_cox_kurtosis)

Skewness: 1.989347671174275
Kurtosis: 5.666687493498708
Log Skewness: -1.0357708633174667
Log Kurtosis: 1.5345947433540923
Sqrt Skewness: 0.6247037340957508
Sqrt Kurtosis: 0.2619484560084735
Box-Cox Skewness: -0.03923807785481781
Box-Cox Kurtosis: -0.26949896454093647


In [39]:
import numpy as np
import pandas as pd
from scipy import stats

# Generate some data with high kurtosis
data = np.random.normal(0, 5, 1000)**3

# Calculate skewness and kurtosis
skewness = stats.skew(data)
kurtosis = stats.kurtosis(data)

print("Skewness:", skewness)
print("Kurtosis:", kurtosis)

# Log transformation
log_data = np.log(data)
log_skewness = stats.skew(log_data)
log_kurtosis = stats.kurtosis(log_data)

Skewness: -0.9386033484128025
Kurtosis: 48.20623396227437


<ipython-input-39-f3a85f4b1985>:16: RuntimeWarning: invalid value encountered in log
  log_data = np.log(data)


In [40]:
# # Import libraries
# import pandas as pd
# import numpy as np
# from sklearn.preprocessing import StandardScaler
# from statsmodels.tsa.arima_model import ARIMA
# from keras.models import Sequential
# from keras.layers import LSTM, Dense

# # Load time-series data
# data = pd.read_csv('time_series_data.csv')

# # Preprocess data
# data.fillna(method='ffill', inplace=True)
# data = data[(data['date'] > '2020-01-01') & (data['date'] < '2021-12-31')]
# data.set_index('date', inplace=True)
# scaler = StandardScaler()
# data = scaler.fit_transform(data)

# # Extract features
# rolling_mean = data.rolling(window=7).mean()
# fft = np.fft.fft(data)
# wavelet = pywt.dwt(data, 'db1')

# # Train ARIMA model
# model = ARIMA(data, order=(1, 1, 1))
# model_fit = model.fit(disp=0)
# predictions = model_fit.predict(start='2022-01-01', end='2022-12-31')

# # Train LSTM model
# X_train, y_train = [], []
# for i in range(7, len(data)):
#     X_train.append(data[i-7:i, 0])
#     y_train.append(data[i, 0])
# X_train, y_train = np.array(X_train), np.array(y_train)

# X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

# # Define the LSTM model
# model = Sequential()
# model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], 1)))
# model.add(Dropout(0.2))
# model.add(LSTM(units=50, return_sequences=True))
# model.add(Dropout(0.2))
# model.add(LSTM(units=50))
# model.add(Dropout(0.2))
# model.add(Dense(units=1))

# # Compile the model
# model.compile(optimizer='adam', loss='mean_squared_error')

# # Fit the model to the training data
# model.fit(X_train, y_train, epochs=100, batch_size=32)

In [42]:
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk
nltk.download('punkt')

text = "This is a sample sentence. It contains some words."
words = word_tokenize(text)
sentences = sent_tokenize(text)

print(words)
print(sentences)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['This', 'is', 'a', 'sample', 'sentence', '.', 'It', 'contains', 'some', 'words', '.']
['This is a sample sentence.', 'It contains some words.']


In [44]:
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words if word.casefold() not in stop_words]

print(filtered_words)

['sample', 'sentence', '.', 'contains', 'words', '.']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [46]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
nltk.download('wordnet')

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

stemmed_words = [stemmer.stem(word) for word in filtered_words]
lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]

print(stemmed_words)
print(lemmatized_words)

[nltk_data] Downloading package wordnet to /root/nltk_data...


['sampl', 'sentenc', '.', 'contain', 'word', '.']
['sample', 'sentence', '.', 'contains', 'word', '.']


In [47]:
import re

def normalize_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\b(can\'t|won\'t|shouldn\'t)\b', 'not', text)
    text = re.sub(r'\b(i\'m|you\'re|he\'s|she\'s|it\'s|we\'re|they\'re)\b', 'be', text)
    return text

text = "I can't believe it's not butter!"
normalized_text = normalize_text(text)

print(normalized_text)

i cant believe its not butter
