[Reference](https://priya-reddy.medium.com/the-best-machine-learning-frameworks-extensions-for-scikit-learn-7e8ca2b1a048)

# Sklearn-pandas


In [2]:
import pandas as pd

In [3]:
data =pd.DataFrame({ 
    'Name':['Ken','Jeff','John','Mike','Andrew','Ann','Sylvia','Dorothy','Emily','Loyford'], 
    'Age':[31,52,56,12,45,50,78,85,46,135], 
    'Phone':[52,79,80,75,43,125,74,44,85,45], 
    'Uni':['One','Two','Three','One','Two','Three','One','Two','Three','One'] 
})
data

Name  Age  Phone    Uni
0      Ken   31     52    One
1     Jeff   52     79    Two
2     John   56     80  Three
3     Mike   12     75    One
4   Andrew   45     43    Two
5      Ann   50    125  Three
6   Sylvia   78     74    One
7  Dorothy   85     44    Two
8    Emily   46     85  Three
9  Loyford  135     45    One

In [7]:
from sklearn_pandas import DataFrameMapper 
import sklearn

mapper = DataFrameMapper([ 
    ('Uni', sklearn.preprocessing.LabelBinarizer()), 
    (['Age'], sklearn.preprocessing.StandardScaler()) 
])

In [8]:
mapper.fit_transform(data)

array([[ 1.        ,  0.        ,  0.        , -0.87202452],
       [ 0.        ,  0.        ,  1.        , -0.21800613],
       [ 0.        ,  1.        ,  0.        , -0.0934312 ],
       [ 1.        ,  0.        ,  0.        , -1.46375545],
       [ 0.        ,  0.        ,  1.        , -0.43601226],
       [ 0.        ,  1.        ,  0.        , -0.2802936 ],
       [ 1.        ,  0.        ,  0.        ,  0.59173093],
       [ 0.        ,  0.        ,  1.        ,  0.80973706],
       [ 0.        ,  1.        ,  0.        , -0.40486853],
       [ 1.        ,  0.        ,  0.        ,  2.36692371]])

In [9]:
mapper.transformed_names_

['Uni_One', 'Uni_Three', 'Uni_Two', 'Age']

In [10]:
mapper = DataFrameMapper([ 
    ('Uni', sklearn.preprocessing.LabelBinarizer()), 
    (['Age'], sklearn.preprocessing.StandardScaler()) 
],df_out=True)

# Sklearn-xarray


In [11]:
import numpy as np 
import xarray as xr 
data = np.random.rand(16, 4) 
my_xarray = xr.DataArray(data)

In [12]:
my_xarray

<xarray.DataArray (dim_0: 16, dim_1: 4)>
array([[0.95718452, 0.0316235 , 0.02563439, 0.35594715],
       [0.92930265, 0.77227031, 0.71774591, 0.48990594],
       [0.57241228, 0.44893651, 0.15132517, 0.2504875 ],
       [0.96560705, 0.9264077 , 0.86976108, 0.79893369],
       [0.14789398, 0.54540085, 0.02670014, 0.21318057],
       [0.73587282, 0.37392066, 0.52000329, 0.43091378],
       [0.73833269, 0.98143663, 0.11142599, 0.27100623],
       [0.37889111, 0.94170793, 0.94809619, 0.19207899],
       [0.8352321 , 0.180521  , 0.52565018, 0.70396139],
       [0.60266744, 0.41644478, 0.00371084, 0.33182968],
       [0.35742785, 0.27491833, 0.6740481 , 0.65393692],
       [0.10629233, 0.09439394, 0.1729089 , 0.44940285],
       [0.72793388, 0.14668533, 0.65603385, 0.3502397 ],
       [0.09814092, 0.61324792, 0.35112548, 0.71383787],
       [0.55418903, 0.03883359, 0.41493094, 0.92179964],
       [0.39947193, 0.83824937, 0.02888335, 0.12714569]])
Dimensions without coordinates: dim_0, dim_1

In [17]:
!pip install sklearn-xarray

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for sklearn-xarray: filename=sklearn_xarray-0.4.0-py3-none-any.whl size=37281 sha256=92181453cd014b6802869f48a247c50d29cc3d135135942462bb19fe89fe0659
  Stored in directory: /root/.cache/pip/wheels/b4/78/78/16bea4e733bb940b948d62d47a992fe799038e488f2950af20
Successfully built sklearn-xarray


In [19]:
from sklearn.preprocessing import StandardScaler 
from sklearn_xarray.datasets import load_dummy_dataarray
from sklearn_xarray import wrap

X = load_dummy_dataarray()
Xt = wrap(StandardScaler()).fit_transform(X)
Xt

<xarray.DataArray (sample: 100, feature: 10)>
array([[-7.98197076e-01,  1.29719242e+00,  8.63448540e-01,
        -1.14751063e+00,  2.33422806e-01, -8.18866173e-01,
        -7.08713469e-01,  3.64890533e-01, -8.21857189e-01,
         1.27332328e+00],
       [-7.83049380e-01, -1.00615384e+00,  1.29145005e+00,
         4.58293742e-01, -1.43727220e+00, -1.34484643e+00,
         4.19520231e-01, -3.38266635e-01, -1.37422158e+00,
         5.21206288e-01],
       [-1.42429823e+00, -9.14197242e-01, -1.44248959e+00,
         2.79973957e-01,  7.28241688e-01,  8.02734488e-01,
         4.76938822e-02, -7.65377651e-01, -6.71745468e-01,
         5.30975404e-01],
       [ 1.10693491e+00,  1.46033629e+00, -1.10428612e+00,
         2.01537133e+00,  7.61577168e-01,  6.53216823e-01,
         5.92164036e-01,  1.51203523e+00, -4.26140033e-01,
        -1.02070367e+00],
       [ 1.93429346e-01, -9.98415403e-01, -1.10324276e+00,
        -5.89173289e-01,  1.29256114e+00,  1.16947837e-01,
        -3.69197665e-01, -1.16338717e+00,  1.67289257e+00,
         1.05816475e+00],
...
       [-1.33588062e+00,  3.65285603e-03,  6.70749498e-01,
         2.03020070e-01,  2.20989812e-01, -1.04289872e+00,
         1.08112059e+00, -7.41407485e-01, -1.03735026e+00,
        -3.74527467e-01],
       [ 1.42807581e+00,  1.11082004e+00, -1.18193151e+00,
        -5.55568859e-01,  1.15105691e+00,  1.60699155e+00,
        -1.23376984e+00,  7.81831989e-01,  8.91891094e-02,
         9.75229184e-01],
       [-2.70210597e-01, -6.77348363e-01,  1.39220756e+00,
         5.25245325e-01,  9.04885459e-01, -1.13876727e+00,
         4.18292207e-01,  1.26794643e+00, -4.56146083e-01,
         2.78982019e-01],
       [ 1.65902907e+00,  8.73774509e-01, -6.88655593e-01,
        -1.00202035e+00, -2.81483320e-01, -8.06865418e-01,
         3.77817497e-01, -2.98208229e-01,  1.63991705e+00,
         1.68064190e+00],
       [-1.78601875e+00, -1.45798922e+00, -7.76412591e-01,
         7.94247763e-01,  2.60108291e-01, -5.69849455e-01,
         6.29357904e-01, -1.07359874e+00,  1.26146734e+00,
         1.10219821e+00]])
Coordinates:
  * sample   (sample) int64 0 1 2 3 4 5 6 7 8 9 ... 91 92 93 94 95 96 97 98 99
  * feature  (feature) int64 0 1 2 3 4 5 6 7 8 9

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([ 
    ('pca', wrap(PCA(n_components=50), reshapes='feature')), 
    ('cls', wrap(LogisticRegression(), reshapes='feature')) 
])


In [24]:
from sklearn_xarray.model_selection import CrossValidatorWrapper
from sklearn.model_selection import GridSearchCV, KFold 
cv = CrossValidatorWrapper(KFold()) 
pipeline = Pipeline([ 
    ('pca', wrap(PCA(), reshapes='feature')), 
    ('cls', wrap(LogisticRegression(), reshapes='feature')) 
]) 
gridsearch = GridSearchCV( 
    pipeline, cv=cv, param_grid={'pca__n_components': [20, 40, 60]} 
)

# Auto-sklearn


In [ ]:
# $ curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install

In [28]:
!pip install auto-sklearn

     |████████████████████████████████| 6.4 MB 3.7 MB/s 
     |████████████████████████████████| 38.1 MB 1.2 MB/s 
     |████████████████████████████████| 22.3 MB 1.4 MB/s 
     |████████████████████████████████| 1.1 MB 44.2 MB/s 
     |████████████████████████████████| 837 kB 33.8 MB/s 
     |████████████████████████████████| 4.3 MB 28.5 MB/s 
     |████████████████████████████████| 4.0 MB 23.3 MB/s 
     |████████████████████████████████| 260 kB 38.5 MB/s 
     |████████████████████████████████| 134 kB 38.1 MB/s 
     |████████████████████████████████| 596 kB 68.7 MB/s 
     |████████████████████████████████| 45 kB 3.4 MB/s 
  Created wheel for auto-sklearn: filename=auto_sklearn-0.14.6-py3-none-any.whl size=6602835 sha256=fc043ae99c74523c584f588508f0035f331f4f188bd3c51e1d193ca9f51973b9
  Stored in directory: /root/.cache/pip/wheels/6a/70/48/db9c00457f87a751083ca0d5c99bf34387dde818c705bd9800
  Created wheel for pynisher: filename=pynisher-0.6.4-py3-none-any.whl size=7043 sha256=7d688

In [31]:
from autosklearn.classification import AutoSklearnClassifier 
cls = AutoSklearnClassifier() 
cls.fit(X_train, y_train) 
predictions = cls.predict(X_test)

# TPOT — Tree-based Pipeline Optimization Tool


In [34]:
!pip install tpot

     |████████████████████████████████| 87 kB 2.4 MB/s 
     |████████████████████████████████| 173.6 MB 9.1 kB/s 
     |████████████████████████████████| 160 kB 43.0 MB/s 
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11956 sha256=67b9a400b101ab273ffcc380d28dee1c15f71770f18cdb19245454121d2baa0f
  Stored in directory: /root/.cache/pip/wheels/e2/d2/79/eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built stopit
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90


In [36]:
from tpot import TPOTClassifier 
from sklearn.datasets import load_digits 
from sklearn.model_selection import train_test_split 
digits = load_digits() 
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, train_size=0.75, test_size=0.25, random_state=42) 
tpot = TPOTClassifier(generations=5, population_size=50, verbosity=2, random_state=42) 
tpot.fit(X_train, y_train) 
print(tpot.score(X_test, y_test)) 
tpot.export('tpot_digits_pipeline.py')