[Reference](https://medium.com/geekculture/fit-vs-transform-vs-fit-transform-in-python-scikit-learn-2623d5a691e3)

In [1]:
"""
scikit-learn example for MinMaxScaler.fit()
"""
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler


# Create dummy features
X, y = np.arange(10).reshape((5, 2)), range(5)

# Create test and train sets
X_train, X_test, y_train, y_test = train_test_split(
	X, y, 
	test_size=0.33, 
	random_state=42
)

print(X_train)
# [[4 5]
#  [0 1]
#  [6 7]]

print(X_test)
# [[2 3]
#  [8 9]]

# Compute the minimum and maximum to be used for later scaling
scaler = MinMaxScaler()
scaler.fit(X_train)

[[4 5]
 [0 1]
 [6 7]]
[[2 3]
 [8 9]]


MinMaxScaler(copy=True, feature_range=(0, 1))

In [2]:
print(f'min_: {scaler.min_}')

print(f'scale_: {scaler.scale_}')

print(f'data_min_: {scaler.data_min_}')

print(f'data_max_: {scaler.data_max_}')

print(f'data_range_: {scaler.data_range_}')

print(f'n_samples_seen_: {scaler.n_samples_seen_}')

min_: [ 0.         -0.16666667]
scale_: [0.16666667 0.16666667]
data_min_: [0. 1.]
data_max_: [6. 7.]
data_range_: [6. 6.]
n_samples_seen_: 3


In [3]:
# Transform/scale test features using the min/max computed 
# from training features
X_train_scaled  = scaler.transform(X_train)

# Transform/scale test features using the min/max computed 
# from training features
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled)

print(X_test_scaled)

[[0.66666667 0.66666667]
 [0.         0.        ]
 [1.         1.        ]]
[[0.33333333 0.33333333]
 [1.33333333 1.33333333]]


In [4]:
scaler = MinMaxScaler()
scaler.transform(X_train)

NotFittedError: ignored

In [5]:
"""
scikit-learn example for MinMaxScaler.fit_transform()
"""
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler


# Create dummy features
X, y = np.arange(10).reshape((5, 2)), range(5)

# Create test and train sets
X_train, X_test, y_train, y_test = train_test_split(
	X, y, 
	test_size=0.33, 
	random_state=42
)

print(X_train)
# [[4 5]
#  [0 1]
#  [6 7]]

print(X_test)
# [[2 3]
#  [8 9]]

scaler = MinMaxScaler()
X_train_scaled  = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

[[4 5]
 [0 1]
 [6 7]]
[[2 3]
 [8 9]]


In [6]:
print(X_train_scaled)

print(X_test_scaled)

[[0.66666667 0.66666667]
 [0.         0.        ]
 [1.         1.        ]]
[[0.33333333 0.33333333]
 [1.33333333 1.33333333]]
