[Reference](https://ai.plainenglish.io/predicting-on-a-multiple-time-series-dataset-8539d080ac72)

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/TracyRenee61/Multiple-Time-Series-Predictions/main/Sales_Transactions_Dataset_Weekly.csv')
data = data.filter(regex=r'Product|W')
data

Product_Code  W0  W1  W2  W3  W4  W5  ...  W45  W46  W47  W48  W49  W50  W51
0             P1  11  12  10   8  13  12  ...   10   12    3    7    6    5   10
1             P2   7   6   3   2   7   1  ...    1    1    4    5    1    6    0
2             P3   7  11   8   9  10   8  ...    5    7    8   14    8    8    7
3             P4  12   8  13   5   9   6  ...    4    6    8   14    8    7    8
4             P5   8   5  13  11   6   7  ...   12    6    6    5   11    8    9
..           ...  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...
806         P815   0   0   1   0   0   2  ...    0    0    1    0    0    2    0
807         P816   0   1   0   0   1   2  ...    2    4    5    5    5    6    5
808         P817   1   0   0   0   1   1  ...    2    2    0    0    0    4    3
809         P818   0   0   0   1   0   0  ...    1    1    0    0    0    2    0
810         P819   0   1   0   0   0   0  ...    0    0    0    0    0    0    1

[811 rows x 53 columns]

In [3]:
data.isnull().sum().sum()

0

In [4]:
code = data.Product_Code

data = data.drop(['Product_Code'], axis=1)

#split the dataset in two
# the last column is our label
y_train = data.iloc[:,-1:].values
#drop last column of data
X_train = data.iloc[:, :-1]
#drop first colum of data
X_test = data.iloc[:,1:]
# lets have a look on the shape 
X_train.shape,y_train.shape, X_test.shape

((811, 51), (811, 1), (811, 51))

In [5]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Define the scaler 
scaler = StandardScaler().fit(X_train)
# Scale the train set
X_train = scaler.transform(X_train)
# Scale the validation set
#X_val = scaler.transform(X_val)
# Scale the test set
X_test = scaler.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:488: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- W51
Feature names seen at fit time, yet now missing:
- W0

  warnings.warn(message, FutureWarning)


In [6]:
from sklearn.neural_network import MLPRegressor

model = MLPRegressor(max_iter=3000, solver='lbfgs', random_state=1, verbose=True).fit(X_train, y_train)
y_pred = model.predict(X_train)
y_pred = y_pred.astype(int)
y_pred

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


array([ 9,  0,  7,  8,  9,  5,  1,  9, 13, 19, 20,  3,  5, 17, 19, 21, 24,
       23, 28,  9,  4,  4,  0, 13, 19, 20, 28, 24, 16, 21,  6,  6, 11, 25,
       27, 18, 28, 23, 25, 22, 26, 15, 27, 16, 20, 13, 19, 27, 23,  9,  7,
       19,  9, 25, 24, 18, 19, 30, 13, 21, 25, 10, 19, 18,  7, 23, 24,  6,
       22, 30,  5, 22, 18, 10, 24, 14,  6, 19, 20, 24, 11,  6, 32, 21, 15,
       25, 23, 24, 28, 18,  9, 18,  9,  8, 14, 21, 24,  5, 10, 21, 14, 29,
        5,  3,  3, 20, 19,  3, 10,  7,  9, 35, 16,  8, 10, 12,  1,  9, 18,
       31, 12, 11,  3,  4,  5,  5,  0, 22, 21, 14, 24, 19, 16, 25, 16, 16,
       28, 24, 23, 29, 22, 25, 23, 11,  7, 12,  2,  6,  5,  2,  4, 10,  9,
        6,  4,  3,  5,  5,  6, 11,  6, 13,  3,  9, 11, 11, 27, 17, 32, 31,
        9, 24, 14, 23, 18, 12, 27, 26, 25, 15, 15, 20, 18, 29, 27, 20, 28,
       24, 22, 30, 23, 31, 20, 26,  2, 27,  9, 15,  2, 25,  3, 23,  6,  3,
       16,  5, 12, 45, 14, 13, 13,  1,  0,  0,  0,  1,  0,  0,  0,  0,  1,
        1,  0,  0,  0,  0

In [7]:
print(model.score(X_train, y_train))

0.9995565851614675


In [9]:
prediction = model.predict(X_test)
prediction = prediction.astype(int)
prediction

array([10,  4, 11,  9, 10, 10,  5, 12, 17, 15, 13, 10,  9, 19, 17, 24, 35,
       28, 29,  9, 11, 13,  1, 25, 19, 10, 29, 13,  7, 17, 13,  9, 14, 27,
       29, 38, 22, 27, 36, 19, 18,  7,  4, 34, 51, 27, 12, 19, 22, -1, 20,
       27,  7, 14, 15, 24, 30, 13, 10, 24,  6, 13, 15, 14, 20, 19, 15,  5,
       34, 18, -3, 15,  1,  8, 17, 30,  1, 30, 18, 11, 21,  7, 27, 32,  5,
       10, 17, 23, 11, 11, 14, 22,  1,  2, 33, 18, 21,  3, 15, 33, 20, 40,
       14, -3, -5, 20, 14,  3,  3,  5, -2, 36, 13, -4, 13,  5,  3, 12, 20,
       17, 18, -1,  3, 11, 17,  8, 11, 10, 21, 23, 20, 11, 23, 20, 21,  9,
       31, 35, 19, 20, 19, 26, 32,  8,  7, 12,  4,  1,  0,  7,  0, 12,  2,
        3,  5,  4,  3,  5,  3,  8,  2,  4,  8, 14, 10, 26, 15, 28, 15, 46,
        7, 24, 22, 21, 27, 39, 28,  5, 19, 39, 17,  9, 15, 25, 11, 12, 53,
       22, 38, 34, 31, 26, 39, 17,  0, 23, 23, 14,  8, 25,  8, 14,  1,  3,
       17,  8,  8, 21, 10,  7,  7,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [10]:
print ('Compare y_train to y_pred: {0}'.format((y_pred == y_train).sum().astype(float) / len(prediction)))

Compare y_train to y_pred: 62.24414303329223


In [11]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_train, y_pred, squared=False)
rmse

0.6836112133360357

In [12]:
#create dataframe
output = pd.DataFrame({'code': code, 'sales': prediction})
#create csv
output.to_csv('submission.csv', index=False)
#upload submission
submission = pd.read_csv("submission.csv")
submission

code  sales
0      P1     10
1      P2      4
2      P3     11
3      P4      9
4      P5     10
..    ...    ...
806  P815      3
807  P816      9
808  P817      4
809  P818      0
810  P819      0

[811 rows x 2 columns]

In [13]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=3000, max_depth=15, random_state=1, verbose=True).fit(X_train, y_train)
r_pred = model.predict(X_train)
r_pred = r_pred.astype(int)
r_pred

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 3000 out of 3000 | elapsed:   41.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 3000 out of 3000 | elapsed:    1.0s finished


array([ 9,  2,  7,  7,  9,  5,  2,  9, 13, 21, 17,  4,  6, 16, 20, 22, 24,
       23, 27,  9,  6,  6,  1, 17, 21, 17, 26, 23, 14, 22,  7,  7, 13, 25,
       26, 20, 26, 24, 24, 21, 25, 18, 26, 19, 21, 17, 21, 25, 23,  8, 12,
       21,  7, 25, 24, 20, 21, 28, 11, 22, 24, 12, 20, 19,  9, 23, 24,  7,
       22, 27,  7, 22, 18, 10, 23, 18,  5, 21, 21, 23, 12,  7, 29, 21, 18,
       24, 23, 23, 25, 19,  9, 20,  9,  9, 14, 22, 24,  5, 10, 19, 17, 27,
        7,  4,  4, 17, 20,  4,  9,  7,  8, 31, 19,  8, 10, 11,  3, 10, 20,
       27, 11, 11,  4,  5,  7,  5,  1, 22, 21, 18, 23, 21, 19, 24, 18, 19,
       26, 23, 23, 26, 23, 24, 23, 11,  8, 11,  5,  6,  6,  4,  4, 11,  9,
        7,  4,  4,  6,  4,  6, 10,  5, 11,  4, 10, 10, 10, 26, 19, 30, 28,
        8, 24, 18, 23, 21, 17, 26, 24, 24, 18, 17, 21, 20, 27, 26, 20, 26,
       24, 22, 27, 23, 28, 20, 25,  3, 26, 10, 15,  3, 25,  4, 22,  7,  4,
       18,  4, 10, 37, 13, 15, 13,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  0,  0,  0,  0

In [14]:
print(model.score(X_train, y_train))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


0.9794312749689092


[Parallel(n_jobs=1)]: Done 3000 out of 3000 | elapsed:    1.0s finished


In [15]:
print ('Compare r_pred to y_train: {0}'.format((r_pred == y_train).sum().astype(float) / len(prediction)))

Compare r_pred to y_train: 60.81997533908755


In [16]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_train, r_pred, squared=False)
rmse

1.4951627717186566

In [17]:
r_prediction = model.predict(X_test)
r_prediction = r_prediction.astype(int)
r_prediction

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 3000 out of 3000 | elapsed:    1.0s finished


array([ 8,  5, 10,  9,  8,  5,  5,  8, 11, 21, 13,  5,  9, 15, 23, 23, 22,
       22, 24,  8,  9,  9,  5, 21, 23, 12, 23, 24, 14, 20,  8,  8, 12, 22,
       24, 24, 24, 23, 23, 24, 22, 24, 22, 22, 24, 24, 22, 26, 22,  9, 18,
       24,  5, 23, 24, 21, 21, 22, 10, 23, 23, 14, 22, 23,  9, 23, 22,  8,
       22, 22,  9, 23, 20,  8, 28, 22,  5, 23, 22, 22, 12,  9, 24, 24, 22,
       23, 21, 22, 21, 24,  8, 23,  8,  9, 15, 22, 21,  5, 10, 15, 22, 23,
        8,  5,  4, 13, 22,  4,  9,  9,  5, 25, 24,  8, 11, 10,  4, 10, 23,
       24, 10,  8,  5,  6,  8,  6,  3, 23, 23, 39, 21, 22, 24, 22, 22, 24,
       22, 24, 22, 24, 24, 22, 22, 10,  8,  9,  9,  5,  9,  5,  5,  9,  8,
        8,  5,  5,  8,  5,  5,  7,  6,  8,  6, 10,  9,  8, 22, 24, 23, 22,
        9, 23, 21, 24, 23, 22, 23, 21, 24, 21, 22, 22, 23, 23, 23, 23, 21,
       24, 24, 21, 20, 22, 23, 23,  6, 25,  8, 16,  4, 21,  5, 19,  6,  4,
       18,  5,  7, 29, 13, 16, 13,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  0,  0

In [18]:
#create dataframe
r_output = pd.DataFrame({'code': code, 'sales': prediction})
#create csv
r_output.to_csv('submission.csv', index=False)
#upload submission
r_submission = pd.read_csv("submission.csv")
r_submission

code  sales
0      P1     10
1      P2      4
2      P3     11
3      P4      9
4      P5     10
..    ...    ...
806  P815      3
807  P816      9
808  P817      4
809  P818      0
810  P819      0

[811 rows x 2 columns]

In [19]:
same = 0
not_same = 0

for i in range(len(prediction)):
  if(prediction[i] == r_prediction[i]):
    same = same + 1
  else:
    not_same = not_same + 1
print("Same = ", same)
print("Not the same = ", not_same)

Same =  219
Not the same =  592


In [20]:
print ('Compare two predictions: {0}'.format((prediction == r_prediction).sum().astype(float) / len(prediction)))

Compare two predictions: 0.27003699136868065
