[Reference](https://medium.com/free-code-camp/an-overview-of-principal-component-analysis-6340e3bc4073)

# 1) Load the dataset to a matrix:

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
irisModule = load_iris()
dataset = np.array(irisModule.data)

# 2) Calculate the covariance matrix:

In [2]:
covarianceMatrix = pd.DataFrame(data = np.cov(dataset, rowvar = False), columns = irisModule.feature_names, index = irisModule.feature_names)

In [3]:
covarianceMatrix

sepal length (cm)  ...  petal width (cm)
sepal length (cm)           0.685694  ...          0.516271
sepal width (cm)           -0.042434  ...         -0.121639
petal length (cm)           1.274315  ...          1.295609
petal width (cm)            0.516271  ...          0.581006

[4 rows x 4 columns]

# 3) Calculate the eigenvalues and eigenvectors:

In [4]:
eigenvalues, eigenvectors = np.linalg.eig(covarianceMatrix)

In [5]:
eigenvalues

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [6]:
eigenvectors

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

# 4) Choose the first K eigenvalues (K principal components/axises):

In [7]:
totalSum = sum(eigenvalues)
variablesExplained = [(i / totalSum) for i in sorted(eigenvalues, reverse = True)]

In [8]:
variablesExplained 

[0.9246187232017268,
 0.05306648311706791,
 0.017102609807929672,
 0.005212183873275513]

In [9]:
featureVector = eigenvectors[:,:2]

In [10]:
featureVector

array([[ 0.36138659, -0.65658877],
       [-0.08452251, -0.73016143],
       [ 0.85667061,  0.17337266],
       [ 0.3582892 ,  0.07548102]])

# 5) Build the new reduced dataset:

In [11]:
featureVectorTranspose = np.transpose(featureVector)
datasetTranspose = np.transpose(dataset)
newDatasetTranspose = np.matmul(featureVectorTranspose, datasetTranspose)
newDataset = np.transpose(newDatasetTranspose)