[Reference](https://pub.aimind.so/using-pipelines-in-machine-learning-bb0788b149cc)

In [1]:
# load dataset
from sklearn.datasets import load_iris

data = load_iris()
X = data.data
y = data.target
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [2]:
# split the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression())
])

In [4]:
# Fit the pipeline to the training data
pipeline.fit(X_train, y_train)

# Predict using the fitted pipeline
predictions = pipeline.predict(X_test)

# Evaluate the model
accuracy = pipeline.score(X_test, y_test)
accuracy

1.0

In [5]:
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, FunctionTransformer

s_scaler = StandardScaler()
m_scaler = MinMaxScaler()
s_scaler.fit(X_train[:,:2])
m_scaler.fit(X_train[:,2:])

def preprocessing(X):
    X_copy = np.copy(X)
    X_copy[:,:2] = s_scaler.transform(X[:,:2])
    X_copy[:,2:] = m_scaler.transform(X[:,2:])
    return X_copy

preprocessing_transfomer = FunctionTransformer(preprocessing)

In [6]:
pipeline = Pipeline([
    ('scaler', preprocessing_transfomer),
    ('classifier', LogisticRegression())
])
pipeline

Pipeline(steps=[('scaler',
                 FunctionTransformer(func=<function preprocessing at 0x7f08e05167a0>)),
                ('classifier', LogisticRegression())])

In [7]:
# Fit the pipeline to the training data
pipeline.fit(X_train, y_train)

# Predict using the fitted pipeline
predictions = pipeline.predict(X_test)

# Evaluate the model
accuracy = pipeline.score(X_test, y_test)
accuracy

1.0

In [8]:
from sklearn.base import BaseEstimator, TransformerMixin

class ColumnDropper(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[:,1:]

dropper= ColumnDropper()

X_d = dropper.fit_transform(X)
X_d

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.2],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.6, 1.4, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3

In [9]:
pipeline = Pipeline([
    ('dropper', ColumnDropper()),
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression())
])
pipeline

Pipeline(steps=[('dropper', ColumnDropper()), ('scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [10]:
s_scaler = pipeline.named_steps['scaler']

In [11]:
s_scaler

StandardScaler()