[Reference](https://medium.com/codex/mathematical-operations-with-arrays-and-arrays-7ec2b4d14bbf)

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.7.10 (default, Feb 20 2021, 21:17:23) 
[GCC 7.5.0]


'1.19.5'

In [2]:
mat1 = np.matrix("1,2,3 ; 4,5,6");

In [3]:
type(mat1)

numpy.matrix

In [7]:
mat2 = np.matrix([[1,2,3], [4,5,6]]); 

In [8]:
mat3 = np.matrix([ [0,10,0,0,0], [0,0,20,0,0], [0,0,0,30,0], [0,0,0,0,40], [0,0,0,0,0]]); 

In [9]:
type(mat3)

numpy.matrix

In [10]:
mat3[2, 3]

30

In [11]:
a = np.array([[1,2],[3,4]]);

In [12]:
type(a)

numpy.ndarray

In [13]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [14]:
A = np.mat(a); 

In [15]:
type(A)

numpy.matrix

In [16]:
A * A

matrix([[ 7, 10],
        [15, 22]])

In [17]:
np.dot(a, a)

array([[ 7, 10],
       [15, 22]])

In [18]:
mat5 = np.asmatrix(a);

In [19]:
mat5 * mat5

matrix([[ 7, 10],
        [15, 22]])

In [20]:
array2 = np.asarray(mat5)

array2

array([[1, 2],
       [3, 4]])

In [21]:
array2 * array2

array([[ 1,  4],
       [ 9, 16]])