[Reference](https://medium.com/python-in-plain-english/when-a-list-is-not-enough-python-arrays-11008bd57940)

In [3]:
from array import array

a = array('b', (x for x in range(9)))

In [4]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))

In [5]:
len(floats)

10000000

In [8]:
floats2 = array('d')

In [6]:
with open('floats.bin', 'wb') as file:
    floats.tofile(file)

In [9]:
floats==floats2

False

# Numpy Arrays

In [20]:
import numpy as np

a = np.arange(12)

In [21]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
a.shape

(12,)

In [23]:
a.shape = 3, 4

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a[1]

array([4, 5, 6, 7])

In [26]:
a[1,2]

6

In [27]:
a[:,1]

array([1, 5, 9])

In [29]:
a.transpose()
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])