[Reference](https://towardsdatascience.com/pandas-tips-that-will-save-you-hours-of-head-scratching-31d8572218c9)

In [3]:
import os
import platform
from platform import python_version
!pip install jupyterlab
import jupyterlab
import numpy as np
import pandas as pd

print("System")
print("os name: %s" % os.name)
print("system: %s" % platform.system())
print("release: %s" % platform.release())
print()
print("Python")
print("version: %s" % python_version())
print()
print("Python Packages")
print("jupterlab==%s" % jupyterlab.__version__)
print("pandas==%s" % pd.__version__)
print("numpy==%s" % np.__version__)

     |████████████████████████████████| 7.8MB 2.8MB/s 
     |████████████████████████████████| 61kB 7.2MB/s 
ERROR: nbclient 0.5.0 has requirement jupyter-client>=6.1.5, but you'll have jupyter-client 5.3.5 which is incompatible.
  Found existing installation: jsonschema 2.6.0
    Uninstalling jsonschema-2.6.0:
      Successfully uninstalled jsonschema-2.6.0
System
os name: posix
system: Linux
release: 4.19.112+

Python
version: 3.6.9

Python Packages
jupterlab==2.2.8
pandas==1.0.5
numpy==1.18.5


In [4]:
np.random.seed(42)
np.random.random_sample(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [5]:
np.random.random_sample(10)

array([0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914])

In [6]:
np.random.seed(42)
np.random.random_sample(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [8]:
df = pd.DataFrame(index=[1, 2, 3, 4, 4], data={"col1": ["a", "b", "c", "d", "d"]})
df

col1
1    a
2    b
3    c
4    d
4    d

In [9]:
assert len(df[df.index.duplicated()]) == 0, "Dataframe has duplicates" 

AssertionError: ignored

In [10]:
df.shape

(5, 1)

In [11]:
df_new = df.join(df, lsuffix='_l', rsuffix='_r')
df_new.shape

(7, 2)

In [13]:
df_new

col1_l col1_r
1      a      a
2      b      b
3      c      c
4      d      d
4      d      d
4      d      d
4      d      d

In [17]:
# df = pd.read_clipboard(sep='\s\s+')
# df