[Reference](https://python.plainenglish.io/mastering-python-arrays-for-numerical-computing-352ed82f9e7c)

In [3]:
import numpy as np

# Basic Arithmetic Operations

In [4]:
# Creating two arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Element-wise addition
add_result = array1 + array2
print("Element-wise addition:", add_result)

# Element-wise subtraction
sub_result = array1 - array2
print("Element-wise subtraction:", sub_result)

# Element-wise multiplication
mul_result = array1 * array2
print("Element-wise multiplication:", mul_result)

# Element-wise division
div_result = array1 / array2
print("Element-wise division:", div_result)

Element-wise addition: [ 6  8 10 12]
Element-wise subtraction: [-4 -4 -4 -4]
Element-wise multiplication: [ 5 12 21 32]
Element-wise division: [0.2        0.33333333 0.42857143 0.5       ]


# Universal Functions (ufuncs)

In [5]:
# Creating an array
array = np.array([1, 2, 3, 4])

# Square root of each element
sqrt_result = np.sqrt(array)
print("Square root:", sqrt_result)

# Exponential (e^x) of each element
exp_result = np.exp(array)
print("Exponential:", exp_result)

# Sine of each element
sin_result = np.sin(array)
print("Sine:", sin_result)

# Natural logarithm of each element
log_result = np.log(array)
print("Natural logarithm:", log_result)

Square root: [1.         1.41421356 1.73205081 2.        ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Natural logarithm: [0.         0.69314718 1.09861229 1.38629436]


# Aggregation Functions

In [6]:
# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Sum of all elements
sum_result = np.sum(array)
print("Sum:", sum_result)

# Mean (average) of all elements
mean_result = np.mean(array)
print("Mean:", mean_result)

# Maximum value
max_result = np.max(array)
print("Maximum:", max_result)

# Minimum value
min_result = np.min(array)
print("Minimum:", min_result)

Sum: 15
Mean: 3.0
Maximum: 5
Minimum: 1


# Matrix Operations

In [7]:
# Creating two 2x2 matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix addition
matrix_add = np.add(matrix1, matrix2)
print("Matrix addition:\n", matrix_add)

# Matrix multiplication
matrix_mul = np.dot(matrix1, matrix2)
print("Matrix multiplication:\n", matrix_mul)

# Transpose of a matrix
matrix_transpose = np.transpose(matrix1)
print("Transpose of the first matrix:\n", matrix_transpose)

Matrix addition:
 [[ 6  8]
 [10 12]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of the first matrix:
 [[1 3]
 [2 4]]


# Basic Indexing

In [8]:
# Creating a 1D array
array_1d = np.array([10, 20, 30, 40, 50])

# Accessing elements by index
print("First element:", array_1d[0])
print("Third element:", array_1d[2])
print("Last element:", array_1d[-1])

First element: 10
Third element: 30
Last element: 50


# Slicing

In [9]:
# Creating a 1D array
array_1d = np.array([10, 20, 30, 40, 50])

# Slicing the array
print("Elements from index 1 to 3:", array_1d[1:4])
print("Every second element:", array_1d[::2])
print("Elements from index 2 to the end:", array_1d[2:])

Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
Elements from index 2 to the end: [30 40 50]


# Multi-dimensional Arrays

In [10]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements
print("Element at row 1, column 2:", array_2d[1, 2])
print("First row:", array_2d[0, :])
print("Second column:", array_2d[:, 1])
print("Subarray from rows 0 to 1 and columns 1 to 2:\n", array_2d[0:2, 1:3])

Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Subarray from rows 0 to 1 and columns 1 to 2:
 [[2 3]
 [5 6]]


# Boolean Indexing

In [11]:
# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Boolean indexing
bool_idx = array > 30
print("Boolean index array:", bool_idx)

# Using boolean indexing to filter elements
filtered_array = array[bool_idx]
print("Filtered array:", filtered_array)

Boolean index array: [False False False  True  True]
Filtered array: [40 50]


# Fancy Indexing

In [12]:
# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Fancy indexing
indices = [1, 3, 4]
print("Elements at indices 1, 3, and 4:", array[indices])

Elements at indices 1, 3, and 4: [20 40 50]


# Reshaping Arrays

In [14]:
# Creating a 1D array
array_1d = np.arange(12)
print("Original 1D array:", array_1d)

# Reshaping to a 3x4 2D array
array_2d = array_1d.reshape((3, 4))
print("Reshaped to 3x4 2D array:\n", array_2d)

# Reshaping to a 2x2x3 3D array
array_3d = array_1d.reshape((2, 2, 3))
print("Reshaped to 2x2x3 3D array:\n", array_3d)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3 3D array:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


# Concatenation and Stacking

In [15]:
# Creating two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenating along the first axis
concatenated_array = np.concatenate((array1, array2))
print("Concatenated array:", concatenated_array)

# Creating two 2D arrays
array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[5, 6]])

# Concatenating along the first axis (rows)
concatenated_2d = np.concatenate((array3, array4), axis=0)
print("Concatenated 2D array along rows:\n", concatenated_2d)

Concatenated array: [1 2 3 4 5 6]
Concatenated 2D array along rows:
 [[1 2]
 [3 4]
 [5 6]]


# Splitting Arrays

In [16]:
# Creating a 1D array
array = np.arange(9)

# Splitting the array into 3 sub-arrays
split_array = np.split(array, 3)
print("Split array into 3 sub-arrays:", split_array)

# Creating a 2D array
array2d = np.arange(16).reshape((4, 4))

# Splitting the array into 2 sub-arrays along the rows
split_array2d = np.split(array2d, 2)
print("Split 2D array along rows:\n", split_array2d[0], "\n\n", split_array2d[1])

Split array into 3 sub-arrays: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
Split 2D array along rows:
 [[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]]


# Basic Statistical Functions

In [17]:
import numpy as np

# Creating an array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculating the mean
mean = np.mean(data)
print("Mean:", mean)

# Calculating the median
median = np.median(data)
print("Median:", median)

# Calculating the standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Calculating the variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


# Summarizing Statistics

In [18]:
# Creating an array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculating the minimum value
min_value = np.min(data)
print("Minimum value:", min_value)

# Calculating the maximum value
max_value = np.max(data)
print("Maximum value:", max_value)

# Calculating the sum of all elements
sum_value = np.sum(data)
print("Sum:", sum_value)

# Calculating the product of all elements
product_value = np.prod(data)
print("Product:", product_value)

Minimum value: 1
Maximum value: 10
Sum: 55
Product: 3628800


# Statistical Operations on Multi-dimensional Arrays

In [19]:
# Creating a 2D array
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculating the mean along the rows (axis 1)
mean_rows = np.mean(data_2d, axis=1)
print("Mean along rows:", mean_rows)

# Calculating the mean along the columns (axis 0)
mean_columns = np.mean(data_2d, axis=0)
print("Mean along columns:", mean_columns)

# Calculating the sum along the rows
sum_rows = np.sum(data_2d, axis=1)
print("Sum along rows:", sum_rows)

# Calculating the sum along the columns
sum_columns = np.sum(data_2d, axis=0)
print("Sum along columns:", sum_columns)

Mean along rows: [2. 5. 8.]
Mean along columns: [4. 5. 6.]
Sum along rows: [ 6 15 24]
Sum along columns: [12 15 18]


# Correlation and Covariance

In [20]:
# Creating two arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

# Calculating the correlation coefficient
correlation_matrix = np.corrcoef(x, y)
print("Correlation coefficient matrix:\n", correlation_matrix)

# Calculating the covariance matrix
covariance_matrix = np.cov(x, y)
print("Covariance matrix:\n", covariance_matrix)

Correlation coefficient matrix:
 [[1. 1.]
 [1. 1.]]
Covariance matrix:
 [[  2.5  25. ]
 [ 25.  250. ]]


# Percentiles and Quantiles

In [21]:
# Creating an array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculating the 25th, 50th (median), and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_50 = np.percentile(data, 50)
percentile_75 = np.percentile(data, 75)

print("25th Percentile:", percentile_25)
print("50th Percentile (Median):", percentile_50)
print("75th Percentile:", percentile_75)

# Calculating quantiles (0.25, 0.5, 0.75)
quantiles = np.quantile(data, [0.25, 0.5, 0.75])
print("Quantiles (0.25, 0.5, 0.75):", quantiles)

25th Percentile: 3.25
50th Percentile (Median): 5.5
75th Percentile: 7.75
Quantiles (0.25, 0.5, 0.75): [3.25 5.5  7.75]


# Practical Examples of Broadcasting
## Example 1: Adding a Scalar to an Array

In [22]:
# Creating a 1D array
array = np.array([1, 2, 3])

# Adding a scalar value to the array
result = array + 5
print("Array + scalar:\n", result)

Array + scalar:
 [6 7 8]


## Example 2: Adding Arrays of Different Shapes

In [23]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a 1D array
array_1d = np.array([10, 20, 30])

# Adding the 2D array and the 1D array
result = array_2d + array_1d
print("2D array + 1D array:\n", result)

2D array + 1D array:
 [[11 22 33]
 [14 25 36]]


## Example 3: Broadcasting with Multi-dimensional Arrays

In [24]:
# Creating a 3D array
array_3d = np.array([[[1], [2], [3]], [[4], [5], [6]]])

# Creating a 2D array
array_2d = np.array([[10, 20, 30]])

# Adding the 3D array and the 2D array
result = array_3d + array_2d
print("3D array + 2D array:\n", result)

3D array + 2D array:
 [[[11 21 31]
  [12 22 32]
  [13 23 33]]

 [[14 24 34]
  [15 25 35]
  [16 26 36]]]


# Normalizing Data

In [25]:
# Creating a 2D array representing data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculating the mean and standard deviation
mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)

# Normalizing the data (z-score normalization)
normalized_data = (data - mean) / std_dev
print("Normalized data:\n", normalized_data)

Normalized data:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [26]:
# Creating a 3D array representing an image with 3 color channels (RGB)
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)

# Creating an array representing a color filter (increase brightness)
filter = np.array([10, 20, 30])

# Applying the filter to the image
filtered_image = image + filter
print("Filtered image shape:", filtered_image.shape)

Filtered image shape: (100, 100, 3)


# Working with Multi-dimensional Arrays


In [27]:
# Creating a 3D array
array_3d = np.arange(27).reshape((3, 3, 3))
print("Original 3D array:\n", array_3d)

# Accessing elements
print("Element at position (1, 1, 1):", array_3d[1, 1, 1])

# Slicing the array
slice_3d = array_3d[:, :, 1]
print("Sliced 3D array along the third dimension:\n", slice_3d)

Original 3D array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Element at position (1, 1, 1): 13
Sliced 3D array along the third dimension:
 [[ 1  4  7]
 [10 13 16]
 [19 22 25]]


# Matrix Multiplication

In [28]:
# Creating two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
matrix_product = np.dot(matrix1, matrix2)
print("Matrix product:\n", matrix_product)

Matrix product:
 [[19 22]
 [43 50]]


# Determinant

In [29]:
# Creating a matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculating the determinant
det = np.linalg.det(matrix)
print("Determinant:", det)

Determinant: -2.0000000000000004


# Eigenvalues and Eigenvectors

In [30]:
# Creating a matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculating eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Indexing with Arrays

In [32]:
# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Indexing with another array
indices = np.array([1, 3])
print("Elements at indices 1 and 3:", array[indices])

Elements at indices 1 and 3: [20 40]


# Conditional Indexing

In [33]:
# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Conditional indexing
condition = array > 30
filtered_array = array[condition]
print("Elements greater than 30:", filtered_array)

Elements greater than 30: [40 50]


# Using np.where

In [34]:
# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Using np.where
result = np.where(array > 30, array, -1)
print("Elements greater than 30, else -1:", result)

Elements greater than 30, else -1: [-1 -1 -1 40 50]
