[Reference](https://iaviral.medium.com/most-used-functions-in-numpy-67405b98a717)

In [1]:
import numpy as np

In [2]:
list = [1,3,5,7]
array = np.array(list)
print(array)

[1 3 5 7]


In [3]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [4]:
array = np.array([5,2,7,4,3,9])
array.sort()
print(array)

[2 3 4 5 7 9]


In [5]:
array = np.array([1,1,1,1,2,2,2,3,3,4,4,4,4,5,5,5])
array = np.unique(array)
print(array)

[1 2 3 4 5]


In [6]:
array = np.arange(1,10,2)
print(array)

[1 3 5 7 9]


In [7]:
array = np.linspace(0,20,5)
print(array)

[ 0.  5. 10. 15. 20.]


In [8]:
array = np.array([1,0,3,4,5])
np.put(array,1,2)
print(array)

[1 2 3 4 5]


In [9]:
array = np.array([0,1,2,3,4,5])
np.min(array)

0

In [10]:
array = np.array([0,1,2,3,4,5])
np.max(array)

5

In [11]:
array = np.array([0,1,2,3,4,5])
np.sum(array)

15

In [12]:
array = np.array([0.3,1.4,2.7])
np.around(array)

array([0., 1., 3.])

In [13]:
np.random.randint(0,10,5)

array([6, 6, 2, 7, 4])

In [14]:
array = np.array([0,1,2,3,4,5])
np.random.shuffle(array)
print(array)

[2 0 4 1 3 5]
