[Reference](https://medium.com/analytics-vidhya/numpy-the-very-basics-6ce19206ee22)

In [1]:
import numpy as np

# One dimensional array

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
print(np.array([1,2,'Hello',3,4]))

['1' '2' 'Hello' '3' '4']


# Two-dimensional array

In [6]:
np.array([[1,2,3,4,5], [1,2,3,4,5]])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [7]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [9]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# np.fill((2,3),3.14)

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.randint(0,1,(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# NumPy Attributes

In [23]:
a=np.random.randint(2, (3,4,5))       

print(a.ndim)       
# print(a.nshape)       
print(a.size) #Multiplication of shape values       
print(a.dtype)       
print(a.itemsize)       
# print(a.nbyte)

1
3
int64
8


# Array Indexing

In [24]:
a=np.array([1,2,3,4,5,6,7,8,9])       
a[0]
a[2]

3

In [25]:
a[-1]

9

In [26]:
a[-2]

8

In [28]:
a=np.array([[2,3,4,5,6],                   
            [7,8,9,10,11],                   
            [2,1,5,1,9]])

print(a[0,0])
print(a[1,-1])

2
11


# Array slicing

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:5]

array([0, 1, 2, 3, 4])

In [32]:
x[5:]

array([5, 6, 7, 8, 9])

In [33]:
x[3:7]

array([3, 4, 5, 6])

In [34]:
x[::2]

array([0, 2, 4, 6, 8])

In [35]:
x[1::2]

array([1, 3, 5, 7, 9])

In [36]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
x[6::-2]

array([6, 4, 2, 0])

# Multidimensional array slicing

In [38]:
a=np.array([[2,3,4,5,6],                   
            [7,8,9,10,11],                   
            [2,1,5,1,9]])
a[:2,:3]

array([[2, 3, 4],
       [7, 8, 9]])

In [39]:
a[:2,:1]

array([[2],
       [7]])

In [40]:
a[::-1,::-1]

array([[ 9,  1,  5,  1,  2],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

# Array concatenation and splitting

In [47]:
a= np.array([ 1,2,3,4 ])        
b=np.array([5,6,7,8])        
c=np.array([[10,9,8,7],                   
            [6,5,4,3]])        
d=np.array([[6,5],                    
            [2,1]])        

np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
np.vstack([a,c])

array([[ 1,  2,  3,  4],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

In [49]:
np.hstack([c,d])

array([[10,  9,  8,  7,  6,  5],
       [ 6,  5,  4,  3,  2,  1]])

In [50]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,[3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [51]:
a=np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
upper,lower = np.vsplit(a,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [53]:
left, right= np.hsplit(a,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
